### ISSUE TITLE
DISPLAY variable not being set or exported?

### ISSUE THREAD

**Issue by mrj** [mate-desktop/mate-session-manager#108]
I'm not sure whether this is a current mate-session-manager problem, but when I upgraded from Fedora 21 to Fedora 23 (Mate 1.10.2), programs started via a desktop or panel icon on my second monitor -- which has been set to be a separate X-screen (:0.1) -- now come up on my first X-screen (:0) instead of correctly on the second screen.

If I add an "env DISPLAY=:0.1 " prefix to the launcher command for an icon, its program then comes up properly on the second monitor.

If I open a terminal on the second screen (right-click on desktop => Open In Terminal) then start programs via the command line, they again properly come up on the second screen.

**Comment by raveit65** [comment]
With my f23 installations fresh from f23 livecd i don't see the behaviour.
Also, there is no different between packages version  from f21/f22/f23, they use all the same tarballs from mate.
Try to create a second account for testing it there.

**Comment by mrj** [comment]
Same behaviour on a new account.

If Mate hasn't changed, it must be something else.

The display driver was and still is the proprietary NVIDIA one (now 304.128) in "Separate X screen" mode. I can try the nouveau driver and its "ZaphodHeads" option, which seems to do the same thing. But the fact that setting DISPLAY is a fix perhaps indicates that the problem lies elsewhere. Was your test on separate X screens?

**Comment by raveit65** [comment]
> The display driver was and still is the proprietary NVIDIA one

This can be the reason for it.
Xorg Heros did a ABI break a few weeks before f23 alpha released.
And nvidia did not updated until now.
You can be lucky that latest availabe nvidia driver works a bit for you.
I use 340xx legacy driver normaly, but with f23 i have no X with this driver.
In result i do not really use f23 until nvidia do an update.

Note, this was not the first time that X folks breaks ABI for no reason in rawhide,
and nvidia linux dev did warn them not to do things like that, otherwise Nvidia will stop to support fedora rawhide very early.

**Comment by mrj** [comment]
Yes, because the NVIDIA proprietary driver doesn't yet support ABI v20, I had to downgrade to xorg-x11-server-Xorg-1.17.4-1.fc22.x86_64 to get it to work in F23. Could this be the cause of the DISPLAY issue?

**Comment by raveit65** [comment]
I think so, downgrading is mostly not enough beause build dependencies changed versions too.
You can try to rebuild the whole X stack from a srpm if you are familar with rpm building.
But first i would try to use nouveau with normal x-server version, to see if that fix the issue.
Maybe nouveau is sufficient for you until nvidia do an update.

**Comment by mrj** [comment]
The proprietary driver works after running the X-server downgrade command `dnf --allowerasing --releasever=22 downgrade xorg-x11-server-Xorg`. But yes, now that nouveau supports the twin-screen mode I want (allowing separate sets of virtual desktops on each monitor), if that fixes the DISPLAY issue, I'll move to it permanently.

Thanks very much for your help. You can close this, because it looks not to be a Mate problem.
