### ISSUE TITLE
mate-session-save as cronjob fails after a while

### ISSUE THREAD

**Issue by der-eismann** [mate-desktop/mate-session-manager#116]
Hey everyone,

I am building a thin client for work, based on a Raspberry Pi 2 with Ubuntu MATE 15.10 (MATE 1.10-2-2). To create the possibility of an automated logout I use a cronjob that checks the idle time with _xprintidle_ and if it's high enough it starts _mate-session-save --force-logout_. This worked perfectly on Ubuntu MATE 15.04 but now it fails.
It works for about 1-2 hours and then suddenly it just doesn't logout anymore. Then everytime the cronjob starts I get the error
*\* (mate-session-save:12525): WARNING **: Failed to call logout: The name org.mate.SessionManager was not provided by any .service files

After a reboot this starts from the beginning, it works for an hour and then the error happens. Any idea for the reason?
##

**Comment by der-eismann** [comment]
Still no answer?

**Comment by flexiondotorg** [comment]
Is this still and issue?
