### ISSUE TITLE
[1.12.0] mate-session-save --shutdown-dialog Restart and Shutdown causes dirty shutdown

### ISSUE THREAD

**Issue by vladbacchus** [mate-desktop/mate-session-manager#119]
Mate 1.12.0, Linux Mint 17.3, Linux  4.4.0-18-generic #34~14.04.1-Ubuntu SMP Thu Apr 7 18:31:54 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux [and recommended kernel]
An interesting issue.  When a computer is very fast, with multiple SSDs in a RAID 0, and mate-session-save --shutdown-dialog, Restart or Reboot is invoked, the "/" is not shutdown cleanly (/ partition is not synced) and a fsck is required each reboot.  The only workaround I have come up with is to change permissions for /sbin/shutdown to allow non root execution and to modify /usr/lib/linuxmint/mintMenu/plugins/system_managment.py;
Original:
if ( self.showQuit == True ):
                Button7 = easyButton( "system-shutdown", self.iconsize, [_("Quit")], -1, -1 )
                Button7.connect( "clicked", self.ButtonClicked, "mate-session-save --shutdown-dialog" )
                Button7.show()
                self.systemBtnHolder.pack_start( Button7, False, False, 0 )
                self.mintMenuWin.setTooltip( Button7, _("Shutdown, restart, suspend or hibernate") )
Modified:
if ( self.showQuit == True ):
                Button7 = easyButton( "system-shutdown", self.iconsize, [_("SHUTDOWN")], -1, -1 )
                Button7.connect( "clicked", self.ButtonClicked, "/sbin/shutdown -h now" )
                Button7.show()
                self.systemBtnHolder.pack_start( Button7, False, False, 0 )
                self.mintMenuWin.setTooltip( Button7, _("Shuts down the computer NOW!") )

I believe that when a restart or shutdown is invoked via mate-session-save --shutdown-dialog, there are no disk flushing/syncing operations that follow.  Can anyone confirm if mate-session-save --shutdown-dialog Restart or Shutdown actually calls for disk sync?

**Comment by raveit65** [comment]
What is the value of 'Filesystem state' with 'tune2fs -l /dev/your_system_device' after boot ?

I use also 4 SSDs with raid0 at a hardware-raid-controller and i had the same issue with one system partition, i use several fedora/rhel/windows installations in a muti-boot system.
tune2fs showed me ''Filesystem state: clean with errors' after boot and fsck was running.
So fsck didn't repair the partition during boot.
After i run fsck again in another installation, i could reboot to previous installation and fsck did not run again during boot.
You can run fsck from a livecd if this is the issue and you don't use a multi-boot system.

I don't use mintmenu in the culprit installation, but running 'mate-session-save --shutdown-dialog' from command line did not cause the error again.

**Comment by vladbacchus** [comment]
raveit65.  Directly after a reboot;
With mate-session-save --shutdown-dialog, 
I received the same EXT4 system check error [dmesg | grep 'EXT4'].
[    3.245007] EXT4-fs (sda2): INFO: recovery required on readonly filesystem
[    3.245009] EXT4-fs (sda2): write access will be enabled during recovery
[    3.409546] EXT4-fs (sda2): orphan cleanup on readonly fs
[    3.409821] EXT4-fs (sda2): 3 orphan inodes deleted
[    3.409822] EXT4-fs (sda2): recovery complete

[tune2fs -l /dev/sda],
tune2fs 1.42.9 (4-Feb-2014)
tune2fs: Bad magic number in super-block while trying to open /dev/sda
Couldn't find valid filesystem superblock.

I will be right back to post the same results after sync && reboot.

**Comment by vladbacchus** [comment]
Well, I learned about "dbus-send --system --print-reply --dest=org.freedesktop.login1 /org/freedesktop/login1 "org.freedesktop.login1.Manager.PowerOff" boolean:true".  My issue seems to be dbus and not mate-session-save.  At least I learned something.
