### ISSUE TITLE
Does not compile in Manjaro

### ISSUE THREAD

**Issue by JunioCalu** [mate-desktop/mate-session-manager#120]
Initial error:

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether NLS is requested... yes
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/^(.*)\${ <-- HERE ?([A-Z_]+)}?(.*)$/ at /usr/bin/intltool-update line 1065.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ?AC_PACKAGE_NAME}?/ at /usr/bin/intltool-update line 1193.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ?PACKAGE}?/ at /usr/bin/intltool-update line 1194.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ?AC_PACKAGE_VERSION}?/ at /usr/bin/intltool-update line 1195.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ?VERSION}?/ at /usr/bin/intltool-update line 1196.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ?AC_PACKAGE_NAME}?/ at /usr/bin/intltool-update line 1222.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ?PACKAGE}?/ at /usr/bin/intltool-update line 1223.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ?AC_PACKAGE_VERSION}?/ at /usr/bin/intltool-update line 1224.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ?VERSION}?/ at /usr/bin/intltool-update line 1225.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ?\w+}?/ at /usr/bin/intltool-update line 1226.
_____________________________________________________________________________

Secondary error:

  ITMRG  mate-session-properties.desktop
  GEN      org.mate.session.gschema.valid
make[3]: Leaving directory '/home/junio/mate/mate-session-manager-gtk3/trunk/src/mate-session-manager-1.14.0/data'
make[2]: Leaving directory '/home/junio/mate/mate-session-manager-gtk3/trunk/src/mate-session-manager-1.14.0/data'
Making all in doc
make[2]: Entering directory '/home/junio/mate/mate-session-manager-gtk3/trunk/src/mate-session-manager-1.14.0/doc'
Making all in dbus
make[3]: Entering directory '/home/junio/mate/mate-session-manager-gtk3/trunk/src/mate-session-manager-1.14.0/doc/dbus'
make  all-am
make[4]: Entering directory '/home/junio/mate/mate-session-manager-gtk3/trunk/src/mate-session-manager-1.14.0/doc/dbus'
  GEN      mate-session.html
xmlto: /home/junio/mate/mate-session-manager-gtk3/trunk/src/mate-session-manager-1.14.0/doc/dbus/mate-session.xml does not validate (status 3)
xmlto: Fix document syntax or use --skip-validation option
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd
/home/junio/mate/mate-session-manager-gtk3/trunk/src/mate-session-manager-1.14.0/doc/dbus/mate-session.xml:8: warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd"
]>
  ^
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd
warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd"
validity error : Could not load the external subset "http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd"
Document /home/junio/mate/mate-session-manager-gtk3/trunk/src/mate-session-manager-1.14.0/doc/dbus/mate-session.xml does not validate
Makefile:600: recipe for target 'mate-session.html' failed
make[4]: *** [mate-session.html] Error 13
make[4]: Leaving directory '/home/junio/mate/mate-session-manager-gtk3/trunk/src/mate-session-manager-1.14.0/doc/dbus'
Makefile:376: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/home/junio/mate/mate-session-manager-gtk3/trunk/src/mate-session-manager-1.14.0/doc/dbus'
Makefile:424: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/junio/mate/mate-session-manager-gtk3/trunk/src/mate-session-manager-1.14.0/doc'
Makefile:499: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/junio/mate/mate-session-manager-gtk3/trunk/src/mate-session-manager-1.14.0'
Makefile:431: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by monsta** [comment]
Well... does this distro have its own bug tracker?

**Comment by JunioCalu** [comment]
Yes, I believe the arch linux should have a solution to this problem, but has more than a month that the maintainers have not packed the mate 1.14, so I decided to package alone, I think the problem is related to some building dependency updated recently .

**Comment by JunioCalu** [comment]
The problem was corrected by replacing docbook2x by docbook-utils
