### ISSUE TITLE
Ctrl Alt Delete window doesn't get focus on second run

### ISSUE THREAD

**Issue by Yanpas** [mate-desktop/mate-session-manager#123]
Ctrl alt delete keyboard combination shows up system exit actions (shutdown hiberntae etc). After pressing Ctrl Alt delete it is unable to navigate in this dialog cause it is not active
##

**Comment by monsta** [comment]
Ok, https://github.com/mate-desktop/mate-session-manager/pull/149 should fix it.

**Comment by monsta** [comment]
The fix is now released in version 1.18.2.
