### ISSUE TITLE
Add a delay setting to Startup Manager

### ISSUE THREAD

**Issue by Rahtgaz** [mate-desktop/mate-session-manager#127]
It would be useful to have a delay setting when adding new applications to mate-session-properties. Currently we have to manage delayed applications through user-made scripts and with the use of the `sleep` command.

However the number of startup applications that require delayed execution can be substantial on some systems, particularly if they depend on ordered execution or require a fully loaded environment. This is true of applications like Conky, for instance, or Tilda when using transparency with some window managers.
##

**Comment by arxo** [comment]
Very useful idea, indeed. :) I've run into problems with startup applications in need of delays a number of times.

**Comment by gitarra** [comment]
For your information, Linux Mint has this feature available.

See: https://ubuntu-mate.community/t/request-add-startup-delay-to-startup-applications/8876

**Comment by danielw2904** [comment]
https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-settings/modules/cs_startup.py

This is the mint implementation

**Comment by danielw2904** [comment]
Specifically

`if "delay" in self.save_mask.contents:
            key_file.set_string(D_GROUP, "X-GNOME-Autostart-Delay", self.delay)`

**Comment by yetist** [comment]
mate-session support `X-MATE-Autostart-Delay=10` in desktop file, is it enough?

**Comment by vkareh** [comment]
Fixed by #178
