### ISSUE TITLE
Open TCP ports by default on Arch Linux

### ISSUE THREAD

**Issue by AndyRandom** [mate-desktop/mate-session-manager#131]
The MATE Session Handler (/usr/bin/mate-session) default configuration is to listen on a TCP V4 and TCP V6 port.
On all interfaces !
**This is a total unnecessary security risk**.

Package version:
Arch Linux i386 (but very likely on all platforms). mate-session-manager 1.16.0-2 (mate mate-gtk3)

config files etc.
/etc/lightdm/lightdm.conf
[XDMCPServer]
#enabled=false

ps axu | grep -e "X[org]"
/usr/lib/xorg-server/Xorg :0 -seat seat0 -auth /run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch

lsof -i -n -P
COMMAND PID USER FD TYPE DEVICE SIZE/OFF NODE NAME
mate-sess 899 me 13u IPv6 22760 0t0 TCP *:35757 (LISTEN)
mate-sess 899 me 14u IPv4 22761 0t0 TCP *:43365 (LISTEN)

Steps to reproduce:
startx

The software author is aware of the problem:
grep -A1 -ne "security reasons" mate-session-manager-1.16.0/mate-session/gsm-xsmp-server.c
566: * hosts, so for security reasons it would be best if ICE didn't
567- * even open any non-local sockets. So we use an internal ICElib

There are user complains since back from 2014:
https://bbs.archlinux.org/vietopic.php?id=182726
https://bbs.archlinux.de/viewtopic.php?id=25645
with ZERO REACTION ! (and some wrong advise...)
**Is this on purpure to increase the attack area of a default Mate installation ?**
I couldn't find any documentation, nowhere, how to stop that.

Any suggestions ?

**Comment by lots0logs** [comment]
Could you check to see if you have `xtrans` installed? If not, try installing it and then restart your session. Does the issue persist?

**Comment by AndyRandom** [comment]
I installed xtrans.

Name            : xtrans
Version         : 1.3.5-1
Description     : X transport library
Architecture    : any
URL             : http://xorg.freedesktop.org/
Licenses        : custom
Groups          : None
Provides        : None
Depends On      : None
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 307.00 KiB
Packager        : Andreas Radke <andyrtr@archlinux.org>
Build Date      : Wed 24 Sep 2014 05:37:51 NZST
Install Date    : Sun 08 Jan 2017 13:56:42 NZDT
Install Reason  : Explicitly installed

No change. The issue persist.

**Comment by flexiondotorg** [comment]
I've just tested this on Ubuntu MATE 16.04 and the alpha for Ubuntu MATE 17.04. `mate-session-manager` is not listening on any ports or interfaces.

**Comment by lots0logs** [comment]
I'm not able to reproduce this on Arch either. Plus I looked at the code and can find nothing that indicates its possible for this issue to occur.

**Comment by AndyRandom** [comment]
Come on guys don't disgrace yourself.
I recheck it on a yesterday downloaded Manjaro MATE edition.
https://sourceforge.net/projects/manjarolinux-community/files/release/16.10.2/mate/manjaro-mate-16.10.2-stable-x86_64.iso/download
Burn, boot
lsof -i -n -P

**Comment by AndyRandom** [comment]
@flexiondotorg 
Are you spending that thoroughness on all your cases ?
Or have you made an exception for this case to close is as fast as possible ?

**Comment by AndyRandom** [comment]
@lots0logs
Please don't look further into code. It does nothing good.

**Comment by lots0logs** [comment]
Manjaro is not Arch. Have you reproduced the issue in Arch or only in Manjaro?

**Comment by AndyRandom** [comment]
@lots0logs 
Don't bullshit me.
Read the first posting.

**Comment by lots0logs** [comment]
I don't appreciate your tone. If you desire to get an issue resolved, you are going about it entirely the wrong way. I read your post and you have since made conflicting comments. I asked for clarification, if you cant provide it then we can just close this issue.

**Comment by AndyRandom** [comment]
I don't appreciate your lack of action.
A 3+ years public documented security risk and a lot of effort to shut me up and do nothing.
You do not ask clarification. 
A. You did not read the first post (ALL your questions are answered there)
B. You try to move the case from a technical to a personal level, on propose.
A or B ?

**Comment by AndyRandom** [comment]
Go ahead close the issue.
Next step will be Slashdot and the Linux kernel list.
And everyone seeing your incompetence.

**Comment by Enverex** [comment]
I can confirm that I'm seeing a single port open by mate-session on one of my Arch boxes:

```
root@emerald ~ $ netstat --inet -nlp | grep -i mate
tcp        0      0 0.0.0.0:44727           0.0.0.0:*               LISTEN      23557/mate-session
```

MATE session manager version 1.16.0-2.

**Comment by raveit65** [comment]
With or without a firewall i don't have this port open on my fedora box.
```
[root@mother rave]# netstat --inet -nlp | grep -i mate
[root@mother rave]# systemctl stop firewalld.service 
[root@mother rave]# netstat --inet -nlp | grep -i mate
[root@mother rave]# systemctl start firewalld.service 
[root@mother rave]# netstat --inet -nlp | grep -i mate
[root@mother rave]# 
```
Please speak more gently otherwise i will ban you from this report.
Btw. i see no link to a Archlinux report.
As we don't have the issue in fedora/ubuntu i suspected a problem in Archlinux itself.
Is it so hard to post first a issue in a distro to give the package maintainer a chance to verify the issue?

**Comment by Enverex** [comment]
@raveit65 Andy logged it downstream here - https://bugs.archlinux.org/task/52344

**Comment by raveit65** [comment]
> I don't appreciate your lack of action.
> A 3+ years public documented security risk and a lot of effort to shut me up and do nothing.

A forum post ?
In which bugreport this is documented in archlinux?

> Next step will be Slashdot and the Linux kernel list.
> And everyone seeing your incompetence.

LOL......go ahead.......

**Comment by raveit65** [comment]
Date is from  Wednesday, 04 January 2017
Is this 3 years ago?
Again, i don't see any serious  comment by downstream maintainer.
Just a guess......

**Comment by Enverex** [comment]
Did you mean 3 weeks ago? (as it's currently 2017...). Downstream thinks it's an upstream issue, upstream thinks it's a downstream issue.

If you guys can confirm that this shouldn't be happening then I can update the bug on Arch's side.

**Comment by lots0logs** [comment]
This seems likely to be the result of user-specific configuration or other installed application. I just performed a clean install in a VM and mate-session is not listening on any ports:

![2017-01-18_04-12-29-am](https://cloud.githubusercontent.com/assets/4675662/22059919/6b326940-dd34-11e6-849b-e43d7bdb7d9c.png)

**Comment by flexiondotorg** [comment]
Here is a screenshot of the various tests that have been cited running on a fully updated Ubuntu MATE 16.04.1 LTS. There are no open ports, which is Ubuntu policy BTW.

![mate-session-testing](https://cloud.githubusercontent.com/assets/304639/22061286/2a8b0d74-dd6c-11e6-9afb-98cb2b8fed21.png)

**Comment by flexiondotorg** [comment]
@monsta Please can run the same tests on Linux Mint and LMDE?
@XRevan86 Please can run the same tests on openSUSE?
@lukefromdc Please can run the same tests on Debian?

**Comment by flexiondotorg** [comment]
> @flexiondotorg
Are you spending that thoroughness on all your cases ?
Or have you made an exception for this case to close is as fast as possible ?

We have not closed this issue. It was marked _unconfirmed_ because none of the distro maintainers (Fedora, Ubuntu MATE, Antergos) can verify your claim.

**Comment by flexiondotorg** [comment]
Looking at the code, if `xtrans` is available at build time then an internal ICElib method disables connections from remote hosts:

  * https://github.com/mate-desktop/mate-session-manager/blob/master/mate-session/gsm-xsmp-server.c#L42

**Comment by XRevan86** [comment]
@flexiondotorg, happens in openSUSE. mate-session-manager wasn't built with xtrans.
I guess, to fix this issue configure.ac should have more clarification about this or a hard-dependency on xtrans.

**Comment by lots0logs** [comment]
> happens in openSUSE. mate-session-manager wasn't built with xtrans.

The `mate-session-manager` package in the official Arch repos is missing the makedep on xtrans. Once the package is rebuilt, this issue should be resolved. I'll update the report on Arch's bug tracker now....

**Comment by monsta** [comment]
The code in gnome-session is almost the same, with the exception of this commit:
https://git.gnome.org/browse/gnome-session/commit/?id=aa4c9d125012ae94154ce075d62342b63b41a7d9

I guess we should pick it from them.

**Comment by monsta** [comment]
Everyone please try https://github.com/mate-desktop/mate-session-manager/pull/132 if you have some time to test it. I asked some devs for review there, but github apparently only allows asking reviews from those with direct access to the repo.

**Comment by lots0logs** [comment]
I'll try to find some time to test it today. Btw, the Arch package [has been updated](https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/mate-session-manager&id=b41c8389c0d0057f80e236b47c33c8ebca546f15). It should hit the mirrors within the next couple hours. Cheers!

**Comment by Enverex** [comment]
Fantastic. Well at least something good came out of this initial trainwreck of a ticket! Thanks guys.

**Comment by AndyRandom** [comment]
@Enverex and @monsta 
***Thank you very much for your effort to fix this issue.***
