### ISSUE TITLE
Startup Applications doesn't respect NoDisplay=true

### ISSUE THREAD

**Issue by jbicha** [mate-desktop/mate-session-manager#134]
Several years ago, Ubuntu had an initiative to make the Startup Applications window empty by default. This was for two reasons:

1. To make it less intimidating
2. Many of these services should not be disabled by users. And if they are disabled, it results in bugs that may take some time to diagnose.

This was very easy to do: just add `NoDisplay=true` to the `/etc/xdg/autostart` files in the default install.

Since then, GNOME has gone one step further and gnome-session no longer builds the Startup Applications app, but Ubuntu patches it back in.

On Ubuntu (Unity) 16.04, the Startup Applications list should be empty. (Well, this has regressed a bit and there are actually 3 items but I've done some work to clean that up in 16.10 and 17.04 at least.)

But when I use Ubuntu MATE 16.04 and open System>Preferences>Personal>Startup Applications
there are a very long list of services. Many of them should not show up since `NoDisplay=true` is set.

Please do not show items in Startup Applications that have `NoDisplay=true`

**Comment by raveit65** [comment]
> Several years ago, Ubuntu had an initiative to make the Startup Applications window empty by default. 

I don't know if that is true, but than you should report it to ubuntu bug report system.
In all other distros we use startup applications for session.

**Comment by jbicha** [comment]
Please reopen this bug. I think you may have misunderstood the bug.

If a .desktop in `/etc/xdg/autostart` has `NoDisplay=true` it should not be displayed in the Startup Applications app.

**Comment by flexiondotorg** [comment]
As @jbicha says, the bug is autostart applications are not hidden when `NoDisplay=true`. This is a cross distro issue. I suggest this is a feature request, rather than a bug.

**Comment by lukefromdc** [comment]
One problem with this: we need to ensure that users can still disable those services enabled by default in a distro that they do NOT want to use. This is a concern with low resource machines and cases where users don't want to uninstall things but rather not start them by default. If the "startup applications" window is empty, where do users go to find and turn off unused startup programs?

**Comment by vkareh** [comment]
I propose a checkbox to "Show hidden" in the Startup Applications window itself. Perhaps with a warning that disabling hidden processes can result in issues.

Otherwise this feature breaks current user expectations.

**Comment by lukefromdc** [comment]
I second that, so users can show added applications only or also stuff they might want to turn off

**Comment by raveit65** [comment]
Honestly, i don't get why a **linux** user should not see all startup application in a GUI which control session start behaviour.
And believe me mate session starts well if you disable all auto-start apps.
Only mate-settings-daemon shouldn't be disabled.

I am not really a friend to hide settings for users.
This is the main reason why most of us switch from Windows to linux years ago ;)
And as affected user i don't like decisions in most cases were a developer thinks this is good for me.

**Comment by vkareh** [comment]
>  This is the main reason why most of us switch from Windows to linux years ago ;)

I think you meant that's why most of us switched from GNOME to MATE years ago? :wink:
