### ISSUE TITLE
add consolekit2 as an optional dependecy?

### ISSUE THREAD

**Issue by oz123** [mate-desktop/mate-session-manager#135]
I saw that upower is dropped in https://github.com/mate-desktop/mate-session-manager/commit/9923739fe6f161a05078340593bf6a91db13d9be.

Should it be replaced with Consolekit2 in `configure.ac`?

**Comment by monsta** [comment]
ConsoleKit support had been there for some time, it's just new suspend/hibernate functionality in ConsoleKit2 that is now supported. ConsoleKit has no libraries that we might have a build dependency on, and all communication in runtime is done via D-Bus. Therefore, it's up to distro maintainers to add a runtime dependency on ConsoleKit package.

**Comment by oz123** [comment]
How are maintainers supposed to know about this if it is not in configure.ac? Sorry if this sounds dumb... I'm helping with Gentoo ebuilds and until now  my way to find about the dependency was to look there....

**Comment by monsta** [comment]
Well, configure.ac only contains build instructions. I'm not aware of any good cross-distro method to show all the runtime dependencies to the maintainers...

One possible way I could think of is to check runtime deps in other distros.
