### ISSUE TITLE
Shutdown & Log Out dialog windows doesn't get focus when launched from keyboard

### ISSUE THREAD

**Issue by spvkgn** [mate-desktop/mate-session-manager#140]
Shutdown and Log Out dialog windows get focus only when launched by mouse. If I launch it from keyboard (Alt-F1 - System) or with `mate-session-save` command then these windows doesn't get focus.

#### Expected behaviour
Shutdown / Log Out dialog window launched from keyboard or with `mate-session-save` command should be focused as well as when launched by mouse.

#### Actual behaviour
Opened Shutdown / Log Out dialog window is not focused.

#### Steps to reproduce the behaviour
- Press Ctrl-Alt-D to show Desktop
- Launch Shutdown dialog window from keyboard pressing Alt-F1 - Left - Up - Enter
- Opened dialog window is not focused

#### MATE general version
1.18.0

#### Package version
1.18.0-0ubuntu1

#### Linux Distribution
Ubuntu-MATE 17.04 x86_64

**Comment by raveit65** [comment]
Confirmed with fedora 26 and using 'mate-session-save --logout-dialog' or 'mate-session-save --shutdown-dialog'.

**Comment by marosg42** [comment]
Same behaviour when invoked with ctrl-alt-del in Ubuntu Mate Alpha

**Comment by monsta** [comment]
Try https://github.com/mate-desktop/mate-session-manager/pull/149 guys, it works for me.

**Comment by monsta** [comment]
The fix is now released in version 1.18.2.
