### ISSUE TITLE
No task found to invoke shutdown dialog

### ISSUE THREAD

**Issue by marosg42** [mate-desktop/mate-session-manager#144]
#### Expected behaviour
When I use search option in dialog (invoked by superkey) I would like to start typing shutdown and see shutdown option to invoke shutdown dialog. Or power or something obvious.

#### Actual behaviour
This is Ubuntu Mate specific I think - when I use Superkey and start typing, I did not find what to type to invoke shutdown dialog. I tried shutdown and power, nothing was found.

#### Steps to reproduce the behaviour
see Actual behaviour

#### MATE and Linux distro version
Ubuntu Mate 17.10 alpha 2

**Comment by raveit65** [comment]
> This is Ubuntu Mate specific I think - when I use Superkey and start typing,

And why you filed out a report here and not at Ubuntu mate?
Super key is used by mate-menu (ubuntu) and mintmenu (lunuxmint).
...sigh, i hate useless notifications in my mailbox.
The day will come that i unsubscribe to Mate at github, to avoid spam  :-)
