### ISSUE TITLE
mate-session compatibility with elogind

### ISSUE THREAD

**Issue by glensc** [mate-desktop/mate-session-manager#146]
#### Expected behaviour

No [assertion](https://github.com/mate-desktop/mate-session-manager/blob/v1.18.1/mate-session/gsm-systemd.c#L567) in logs, doing similar code path what would happen if systemd-logind was running.

#### Actual behaviour

```
Aug 18 08:52:21 rotten-fruit mate-session[2823]: CRITICAL: gsm_systemd_set_session_idle: assertion 'session_path != NULL' failed
```

#### Steps to reproduce the behaviour

1. install [elogind](https://github.com/elogind/elogind)
2. suspend: `loginctl suspend`
3. wake up using keypress,  mouse, etc

#### MATE general version

1.18

#### Package version

mate-session-manager-1.18.0-1.x86_64

#### Linux Distribution

[PLD Linux](https://www.pld-linux.org/)

**Comment by glensc** [comment]
cross-ref with elogind tracker: https://github.com/elogind/elogind/issues/26

**Comment by joakim-tjernlund** [comment]
I suspect the problem is because MATE does not support elogind. Grepping for elogind
in mate-session sources gives noting.
Adding elogind should be easy though, see  https://bugs.gentoo.org/show_bug.cgi?id=599482
for adding elogind to gvfs

**Comment by joakim-tjernlund** [comment]
The same probably applies to mate-power-manager

**Comment by jorgicio** [comment]
I created an attempt of patch in order to enable elogind for MATE session 1.20.x. You can check it here: https://gist.github.com/jorgicio/dcc3f2f42f15b7426b9497ab68262a0f

I hope it helps.

**Comment by joakim-tjernlund** [comment]
Yes, that is a good start. One thing I suspect needs fixing is:
```
#ifdef defined(HAVE_SYSTEMD) || defined(HAVE_LIBELOGIND)
 #include <systemd/sd-login.h>
#endif
```
I recall elogind has is own include prefix, possibly <logind/sd-login.h> ?
You could try renaming the systemd include dir and see if mate-session still builds.

**Comment by joakim-tjernlund** [comment]
ehh, I migth be wrong. Seems like the include patch now is the same ?

**Comment by joakim-tjernlund** [comment]
@jorgicio, Would be great if you could have a look at mate-power as well.

**Comment by jorgicio** [comment]
@joakim-tjernlund I fixed the patch when I replaced the "ifdef" for "if". I tried that patch and found doesn't work good as well because some apps crash, like mate-panel, which segfaults.
Respect on mate-power, it doesn't depend totally on which are you using (systemd, elogind or consolekit), only at the packaging time (as it happened with Gentoo).

Yes, it's a good start, but there's some more work to do.

**Comment by joakim-tjernlund** [comment]
Do you have a functional elogind DE(like KDE ) ?

Yes, mate-power seems to be a runtime dep only.

**Comment by jorgicio** [comment]
> Do you have a functional elogind DE(like KDE ) ?
> 
> Yes, mate-power seems to be a runtime dep only.

Nope, I only have MATE installed, and I'm not thinking about using another desktop by now.

**Comment by jorgicio** [comment]
> @jorgicio I think you can just define both SYSTEMD and LOGIND in configure.
> That way you don't need to mess with the source code.

You mean define LOGIND as the same way as SYSTEMD?

**Comment by joakim-tjernlund** [comment]
I mean adding a:
 AC_DEFINE([HAVE_SYSTEMD]
inside the new logind configure snipped so that both HAVE_LIBELOGIND and HAVE_SYSTEMD are
defined.

**Comment by joakim-tjernlund** [comment]
@jorgicio Head over to
https://github.com/elogind/elogind/issues/70

**Comment by darkshram** [comment]
@jorgicio Elogind and SystemD are mutually exclusive. So, instead of trying to make patches for everything to recognize elogind, wouldn't it be easier to just ask elogind developers to symlink and own /usr/include/systemd and /usr/lib64/pkgconfig/libsystemd-login.pc? I'm doing some testing in my systemd-less distro to replace ConsoleKit2 and so far everything builds Ok.

**Comment by joakim-tjernlund** [comment]
[0001-Add-LOGIND-support.txt](https://github.com/mate-desktop/mate-session-manager/files/2942508/0001-Add-LOGIND-support.txt)

Dry port to elogind that builds.

**Comment by jorgicio** [comment]
> [0001-Add-LOGIND-support.txt](https://github.com/mate-desktop/mate-session-manager/files/2942508/0001-Add-LOGIND-support.txt)
> 
> Dry port to elogind that builds.

Thanks, I just watched this and I'll try to port this to see what happens.

**Comment by vkareh** [comment]
I've moved the patch as a draft pull request (#195) to track within the project. I also removed the version requirement for libelogind, since I don't know what any version any distro uses (it's not in the Fedora repos, from what I can see). Please head over to #195 to continue the discussion around this patch.

**Comment by jorgicio** [comment]
Just tried there the patch and it works flawlessly. Thanks to @joakim-tjernlund for the patch.

Now it's included in my Gentoo overlay. check jorgicio/mate-elogind-gentoo repo.

**Comment by darkshram** [comment]
I have applied patch in testing packages for my Fedora-based-but-systemd-less distro. Builds pretty good. In a few weeks will issue a BETA liveCD with MATE Desktop using elogind. So far works perfectly with all my test machines.

**Comment by raveit65** [comment]
> I have applied patch in testing packages for my Fedora-based-but-systemd-less distro. Builds pretty good. In a few weeks will issue a BETA liveCD with MATE Desktop using elogind.

I hope you work on redhat bugzilla reports when it caused problems in f30.

**Comment by joakim-tjernlund** [comment]
Thank you Victor :)
