### ISSUE TITLE
mate-about --mate-version yields "unknown option" error

### ISSUE THREAD

**Issue by Sinan81** [mate-desktop/mate-session-manager#148]
Since 'mate-about --version' yields the expected behaviour either man page needs to be updated or this should be considered a bug and fixed accordingly.

#### Expected behaviour
user@host /usr/bin $ mate-about --mate-version
MATE Desktop Environment 1.18.0

#### Actual behaviour
user@host /usr/bin $ mate-about --mate-version
unknown option --mate-version

#### Steps to reproduce the behaviour
Try it for yourself

#### MATE general version
1.18

#### Package version
Package: mate-desktop
Version: 1.18.0-1+sonya
Architecture: amd64
Maintainer: MATE Packaging Team <mate-dev@ml.mate-desktop.org>
Installed-Size: 93
Depends: hicolor-icon-theme, libmate-desktop-2-17, mate-desktop-common (= 1.18.0-1+sonya), libc6 (>= 2.4), libglib2.0-0 (>= 2.28.0), libgtk-3-0 (>= 3.0.0)
Recommends: mate-user-guide
Breaks: mate-desktop-gnome
Replaces: mate-desktop-gnome
Multi-Arch: foreign
Homepage: http://www.mate-desktop.org/
Priority: optional
Section: x11
Filename: pool/backport/m/mate-desktop/mate-desktop_1.18.0-1+sonya_amd64.deb
Size: 25300
SHA256: 59ccc048ccb1f15cc5062cd65b2e46614f9720a500f82276b6a7c1b1ed40cd61
SHA1: fddfb35244897443d81b3152b329af4cf5f5b5ec
MD5sum: 8d59c95534b4dd77bac72fbcc307d315
Description-en: Library with common API for various MATE modules
 The MATE component mate-desktop contains the libmate-desktop library, the
 mate-about program, as well as some desktop-wide documents.
 .
 The libmate-desktop library provides an API shared by several applications
 on the desktop, but that cannot live in the platform for various
 reasons.
 .
 The mate-about program helps with finding which version of MATE is installed.
Description-md5: 00a366bf9bf6902235e7787f948836fd

Package: mate-desktop
Priority: optional
Section: universe/x11
Installed-Size: 90
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: MATE Packaging Team <pkg-mate-team@lists.alioth.debian.org>
Architecture: amd64
Version: 1.12.1-1
Replaces: mate-desktop-gnome
Depends: hicolor-icon-theme, libmate-desktop-2-17 (>= 1.10.0), mate-desktop-common (= 1.12.1-1), mate-user-guide, libc6 (>= 2.4), libglib2.0-0 (>= 2.28.0), libgtk2.0-0 (>= 2.14.0), python
Breaks: mate-desktop-gnome
Filename: pool/universe/m/mate-desktop/mate-desktop_1.12.1-1_amd64.deb
Size: 23800
MD5sum: a9fb9c5260235d46f6cdcf3aaf66b164
SHA1: c665a5ca78119829346d1f5415b959785c252077
SHA256: eaf5286352e81fc794da93d0e525a8e15d17c33209e0ab5fa8bed4713ea1743f
Description-en: Library with common API for various MATE modules
 The MATE component mate-desktop contains the libmate-desktop library, the
 mate-about program, as well as some desktop-wide documents.
 .
 The libmate-desktop library provides an API shared by several applications
 on the desktop, but that cannot live in the platform for various
 reasons.
 .
 The mate-about program helps with finding which version of MATE is installed.
Description-md5: 00a366bf9bf6902235e7787f948836fd
Multi-Arch: foreign
Homepage: http://www.mate-desktop.org/
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu
Supported: 3y
Task: ubuntu-mate-core, ubuntu-mate-desktop, ubuntu-mate-cloudtop

#### Linux Distribution
Linux Mint 18.2

**Comment by monsta** [comment]
Was fixed in https://github.com/mate-desktop/mate-desktop/commit/133c20a27945b1fb370f5a52dc273830aeaa19e8
