### ISSUE TITLE
[Feature Request] Startup Applications - Add .desktop items

### ISSUE THREAD

**Issue by Justinzobel** [mate-desktop/mate-session-manager#150]
Currently MATE Startup Applications requires the user to know the command path of the application. It would be more user friendly to add via an existing .desktop file so it shows the app name and icon.

Example from Budgie Settings:
![image](https://user-images.githubusercontent.com/1370117/32529258-6f070a18-c487-11e7-92f6-933142a3c7ef.png)

**Comment by flexiondotorg** [comment]
Using `.desktop` files alone would prevent people from adding arbitrary custom scripts to their start applications, something I regularly observe users doing.

So while I agree it would be nice to offer a more user friendly way to add desktop applications to auto start, it should not do so at the expense of a adding arbitrary paths to executables.
