### ISSUE TITLE
[Proposal] Remove progress bar in logout dialog

### ISSUE THREAD

**Issue by mrnhmath** [mate-desktop/mate-session-manager#151]
As there is no way to put the timeout text inside the progress bar in gtk3, it goes above the progress bar and things look a bit ugly/unpolished. Consider following the GNOME 2 design:

![](https://user-images.githubusercontent.com/13562431/34447111-148f35a6-ecc8-11e7-8fad-ef0baa8abb50.png)

**Comment by lukefromdc** [comment]
I don't see it as looking unpolished in any way, though this could depend on the theme. I would just as soon keep the progress bar

**Comment by flexiondotorg** [comment]
I'd prefer to keep it too.
