### ISSUE TITLE
User processes are not terminated on logout

### ISSUE THREAD

**Issue by alkisg** [mate-desktop/mate-session-manager#165]
#### Problem description:
User processes are not terminated on logout. Apart from wasting resources, this is causing severe problems on re-logins, for example "cannot acquire bus" or even dconf database corruption.

#### Steps to reproduce:
1. Login
2. Logout
3. Press Alt+Ctrl+F1 to switch to vt1, and login there
4. Run `ps -ef` and see that most of the user processes are still running.

#### Expected behaviour
All other desktop environments properly terminate the user processes on logout.

#### MATE general version
mate 1.20.1

#### Package version
mate-desktop   1.20.1-2ubuntu1 

#### Linux Distribution
Ubuntu MATE 18.04.1

**Comment by alkisg** [comment]
Debian Stretch is also affected by this issue.
Login, logout, and minutes later the user processes are still running.

**Comment by alkisg** [comment]
It also happens on Fedora-MATE_Compiz-Live-x86_64-28-1.1.iso.
Boot the live CD, autologin, logout, Alt+Ctrl+F2, login as liveuser, pgrep -cu liveuser => 17 processes still running.

**Comment by alkisg** [comment]
It does NOT happen on Ubuntu 16.04.5.
So it seems to be a regression affecting all newer MATE releases and distros.

**Comment by alkisg** [comment]
After some more digging, it seems that:
- systemd is supposed to automatically stop these user services when the last PAM session of this user is closed
- LightDM is responsible for closing the PAM session. But it never does, so it appears to be LightDM's fault

Replacing LightDM with GDM indeed makes everything work fine.
I also tested and it affects Lubuntu and Xubuntu 18.04.1 as well.

So I've filed this issue against LightDM: https://github.com/CanonicalLtd/lightdm/issues/45

**Comment by selectiveduplicate** [comment]
Then maybe close this issue?

**Comment by alkisg** [comment]
After a long chat about it in the #systemd IRC channel, here is the explanation as I understood it:
The problem started with systemd separating the concepts of "user session" vs "desktop/xorg session". Services that are ran from `system --user` persist xorg termination. If a user logs in from e.g. xorg and terminal at the same time, and then logs out from xorg, those services are still running until all user PAM sessions are closed. And if the user then logs in again to xorg without ever logging out from the terminal, those services are supposed to be reused.

That means that dbus-daemon is now stopped only after all PAM sessions are closed.
But some MATE programs don't know this and don't terminate with Xorg; they only terminate when dbus-daemon disappears.
So, when exiting xorg, those mate programs are still running and cause the session to be closed.
So the correct fix is for those programs to register with the session manager so that they're killed on logout, so that then systemd realizes that the PAM session is closed, so that `systemd --user` stops all the services.

Example. Here are the services that persist logout:
```
UID        PID  PPID  C STIME TTY      STAT   TIME CMD
ltsp     30367     1  0 13:26 ?        Ss     0:00 /lib/systemd/systemd --user
ltsp     30368 30367  0 13:26 ?        S      0:00 (sd-pam)
ltsp     30490 30367  0 13:26 ?        Ss     0:00 /usr/bin/dbus-daemon --session --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
ltsp     30684 30367  0 13:26 ?        Sl     0:00 /usr/lib/dconf/dconf-service
ltsp     30690     1  0 13:26 ?        Sl     0:00 gnome-keyring-daemon --start
ltsp     30699 30367  0 13:26 ?        Ssl    0:00 /usr/lib/gvfs/gvfsd
ltsp     30704 30367  0 13:26 ?        Sl     0:00 /usr/lib/gvfs/gvfsd-fuse /run/user/1001/gvfs -f -o big_writes
ltsp     30735 30367  0 13:26 ?        Ssl    0:00 /usr/lib/gvfs/gvfs-udisks2-volume-monitor
ltsp     30739 30367  0 13:26 ?        Ssl    0:00 /usr/lib/gvfs/gvfs-gphoto2-volume-monitor
ltsp     30744 30367  0 13:26 ?        Ssl    0:00 /usr/lib/gvfs/gvfs-mtp-volume-monitor
ltsp     30748 30367  0 13:26 ?        Ssl    0:00 /usr/lib/gvfs/gvfs-afc-volume-monitor
ltsp     30753 30367  0 13:26 ?        Ssl    0:00 /usr/lib/gvfs/gvfs-goa-volume-monitor
ltsp     30775     1  0 13:26 ?        Sl     0:00 /usr/lib/deja-dup/deja-dup-monitor
ltsp     30819     1  0 13:26 ?        Sl     0:00 /usr/bin/python3 /usr/share/system-config-printer/applet.py
ltsp     30832     1  0 13:26 ?        Sl     0:00 /usr/lib/x86_64-linux-gnu/indicator-power/indicator-power-service
ltsp     30833     1  0 13:26 ?        Sl     0:00 /usr/lib/x86_64-linux-gnu/indicator-sound/indicator-sound-service
ltsp     30842     1  0 13:26 ?        Sl     0:00 /usr/lib/x86_64-linux-gnu/indicator-session/indicator-session-service
ltsp     30848     1  0 13:26 ?        Sl     0:00 /usr/lib/x86_64-linux-gnu/indicator-messages/indicator-messages-service
ltsp     30861     1  0 13:26 ?        Sl     0:00 /usr/lib/x86_64-linux-gnu/indicator-application/indicator-application-service
ltsp     30901 30367  0 13:26 ?        Dsl    0:00 /usr/lib/gvfs/gvfsd-metadata
ltsp     30916 30699  0 13:26 ?        Sl     0:00 /usr/lib/gvfs/gvfsd-trash --spawner :1.15 /org/gtk/gvfs/exec_spaw/0
ltsp     30955 30367  0 13:26 ?        Ss     0:00 /usr/lib/bluetooth/obexd
```

The applications that have parent pid = 1 should be fixed so that they exit with the session. Now they only exit when dbus exits, which is wrong.
The applications that don't have parent pid = 1 were started by `systemd --user`. Those don't need to be fixed. They will be stopped by systemd when the PAM session is closed, i.e. when the others with PPID=1 are terminated.

The people at #systemd also suggested that while this is the correct thing to do, i.e. fix the applications to exit with the desktop session, in the mean time desktop environments or display managers can also do workarounds, like restarting the dbus-daemon on logout, so that the user services are kicked and terminated. This is probably what gnome-session or gdm do; and it will help if mate-session or lightdm do it as well.

**Comment by alkisg** [comment]
Here is the gnome-session workaround, that mate-session needs to implement as well:
https://gitlab.gnome.org/GNOME/gnome-session/commit/97d1cf5

**Comment by khurshid-alam** [comment]
People at systemd suggests many things. But Debian doesn't go for it, See my comment https://github.com/CanonicalLtd/lightdm/issues/45#issuecomment-433468712

**Comment by alkisg** [comment]
Hi, as I said in [comment 2 above](https://github.com/mate-desktop/mate-session-manager/issues/165#issuecomment-432609836), this happens on Debian too.

**Comment by EmilyBjoerk** [comment]
I am also affected by this on gentoo with OpenRC (ConsoleKit2, PolKit, eudev) instead of systemd. 

Many (all?) processes started by autostart (in my case: pulseaudio, redshift, rdm) remain running when I log out my graphical session.

Pulse audio then goes off the walls crazy when I log in again as it finds another pulse audio daemon running for my user and then both of them use 100% CPU. Which is why I noticed to begin with.
