### ISSUE TITLE
1.20.2: configure doesn't scream when yelp development files are missing

### ISSUE THREAD

**Issue by kyrios123** [mate-desktop/mate-session-manager#181]
#### Expected behaviour
When building from git, configure/autogen doesn't make an error when yelp development files are missing then build fails.

#### Actual behaviour
There should be a check for yelp development files

#### Steps to reproduce the behaviour
lauch autogen/configure on an environment on which yelp isn't installed.

#### MATE general version
1.20.4 (mate-desktop)

#### Package version
1.20.2

#### Linux Distribution
Solus

#### Link to downstream report of your Distribution
I haven't reported this problem downstream as it is more for you to know in case you want to add the missing check in a future version.

**Comment by zhuyaliang** [comment]
@kyrios123 Failed to reproduce the issue, ```yelp``` is not installed in the system, and the compilation and construction of ```mate-session-manager``` are all normal

**Comment by kyrios123** [comment]
ok let's close this then.
