### ISSUE TITLE
mate-session spawns 10 x-caja-desktop windows on first login.

### ISSUE THREAD

**Issue by dmashal** [mate-desktop/mate-session-manager#19]
Apparently marco can't start fast enough or .config/dconf does not get created fast enough for first login and exactly 10 x-caja-desktop windows get spawned.

edit:

If you run mate-session from a terminal you can notice an endless spawning of caja.

I thought switching to metacity would help but in reality it didn't.

I suspect systemd or msd to be the culprit here.

MDykstra is experiencing a similar issue with ArchLinux and systemd 196

Thanks in advance.

![SvSdp](https://f.cloud.github.com/assets/1594430/49919/20c94ab4-5984-11e2-80e8-350a8cbdd3f6.png)

**Comment by farvardin** [comment]
I got this as well (on linux mint current LTS with mate 1.8).
If I start another WM then launch mate-session, I got those errors in the console:

** (caja:10092): WARNING **: Can not determine workarea, guessing at layout
The program 'caja' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadDrawable (invalid Pixmap or Window parameter)'.
  (Details: serial 7 error_code 9 request_code 53 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

I can't start caja as a standalone file manager either.

it seems it's the same error here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=746339

On a similar computer with a similar installation (same linux mint), no problem with mate.

Like the user in the debian bug report, I can only start caja with "caja --sync".

**Comment by aperezbios** [comment]
This appears to be happening to me on an Ubuntu-MATE LiveCD boot (on PowerPC, though I doubt that actually matters) with the latest nightly ISO for Ubuntu 16.10 . Can't seem to shake this issue, eh?

**Comment by monsta** [comment]
Did you file a report on Launchpad (preferably via apport)?

**Comment by Brownegmx** [comment]
I have always experienced this bug from all the versions of MATE I have used, including 1.18, on different machines. For what I know this bug has always been present and still is. It is a real limitation and I suspect if must put-off a lot of people. The option Startup Applications Preferences/Options/Automatic remember... comes off by default at installation as it should while the bug is still not solved. I have not experienced that bug with Gnome 2.

**Comment by raveit65** [comment]
> I have not experienced that bug with Gnome 2.

Please read carefully this report, otherwise you would understand that this dconf related and gnome2  use another config setting system.
And please check if this dir is writable for your user
```
[rave@mother ~]$ ls -ls /var/run/user/1000/dconf/
insgesamt 4
4 -rw------- 1 rave rave 2 24. Apr 13:30 user
```

Is there a reason why you post several reports today without saying which distro and distro-release are you using?
Or

**Comment by Brownegmx** [comment]
I have filed two reports today
        because I have found out today the correlation between the caja
        file rename editing problem and the mouse pointer option.
    I have used MATE with several
        distributions over the years. I presently use it for my
        day-to-day, operational work with the latest versions of
        Ubuntu-MATE-16.04 (MATE-1.12.1) and Mint-MATE-18.1 (MATE-1.16.1)
        on two different machines.
      
    The issue of not being able to
        re-open the desktop in the state it has been left has always been
        present in all the distributions I have used and I can see it is
        still not solved. I have checked the access to the 'user' file
        you mention and I confirm it belongs to the user concerned with
        the read and write access. You suggests I read a report and there
        is no report attached or any reference or link to a report. Can
        you point me to it? I am not qualified to figure out where the
        problem comes from; whether the bug is with MATE or dconf, for
        the users it remains a bug.
      
    Gnome-2 was a great desktop concept
        and implementation. Its being dropped by the Gnome team was, in
        my view, a destructive blow to the credibility of all OSS as an
        operational solution. Thanks to the MATE team for having picked
        up from there. I can see MATE is now offered by most of the
        major distributions which is testimony of the need there is for
        such desktop concept.
    Cheers,
      
    On 24/04/17 12:34, raveit65 wrote:
    
    
      
        I have not experienced that bug with Gnome 2.
      
      Please read carefully this report, otherwise you would
        understand that this dconf related and gnome2 use another config
        setting system.
        And please check if this dir is writable for your user
      [rave@mother ~]$ ls -ls /var/run/user/1000/dconf/
insgesamt 4
4 -rw------- 1 rave rave 2 24. Apr 13:30 user

      Is there a reason why you post several reports today without
        saying which distro and distro-release are you using?
        Or
      —
        You are receiving this because you commented.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mate-desktop/mate-session-manager","title":"mate-desktop/mate-session-manager","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mate-desktop/mate-session-manager"}},"updates":{"snippets":[{"icon":"PERSON","message":"@raveit65 in #19: \u003e I have not experienced that bug with Gnome 2.\r\n\r\nPlease read carefully this report, otherwise you would understand that this dconf related and gnome2  use another config setting system.\r\nAnd please check if this dir is writable for your user\r\n```\r\n[rave@mother ~]$ ls -ls /var/run/user/1000/dconf/\r\ninsgesamt 4\r\n4 -rw------- 1 rave rave 2 24. Apr 13:30 user\r\n```\r\n\r\nIs there a reason why you post several reports today without saying which distro and distro-release are you using?\r\nOr "}],"action":{"name":"View Issue","url":"https://github.com/mate-desktop/mate-session-manager/issues/19#issuecomment-296628307"}}}

**Comment by raveit65** [comment]
Have fun with reading :-)
Link already posted here https://github.com/mate-desktop/mate-session-manager/issues/19#issuecomment-36440079

**Comment by monsta** [comment]
> I have always experienced this bug from all the versions of MATE I have used, including 1.18, on different machines. For what I know this bug has always been present and still is.

Please give us more details. Do you get several "x-caja-desktop" windows on start? Does it stop at some point, or are these windows spawning infinitely?

**Comment by rhiltbrunn** [comment]
I didn't have the exact same problem, but it sounds very close. My problem was infinite Caja windows spawning after startup!

The work-around I found was to edit the "/usr/share/applications/caja.desktop" file by changeing: 
   
    X-MATE-AutoRestart=true
to

    X-MATE-AutoRestart=false

I'm a real novice with Linux, and especially with Ubuntu-Mate, so I don't know what side the effects of this change will be, if any. So far though, this solved my problem. 

I found the answer here:
http://blog.aguilarbros.com

Cheers!

**Comment by midodark** [comment]
i had this problem in ubuntu mate 18.04 lts and i fix it with compiz that you change window manager in mate tweak from marco to compiz

**Comment by pgaltieri** [comment]
This is not a fix.  It's a workaround.  Recommending this as a solution 
means no one is going to fix the real problem.

Paolo

**Comment by lukefromdc** [comment]
I have not seen this happen in many years, not sure if it was with 1.8 that this happened but that time sounds about right. It was something that happened seeminly at random and usually created an infinate number of windows.

More recently, I had to do a great deal of work after the port of caja from libunique to GtkApplication to deal with a "startup loop" condition caused  by the combination of 
org>mate>caja>preferences>exit-with-last-window = TRUE (not default)
with 
org>mate>desktop>background>show-desktop-icons = FALSE (not default)
and also combined with 
org>mate>desktop>session>required-components>filemanager=caja (default)
which forces Caja to start, close from not having any open windows (no desktop window) and then restart again from the session manager. The initial decision I recall was to match the previous behavior of the libunique version, which used to throw an infinately growing number of non-openable caja window buttons in the panel. Now thaqt combination just loops silently and loads the CPU but is still an irrational configuration that would most likely appear by accident.

It would be possible to add code to caja to catch that triplet and simply block the exit, as it is not possible from within Caja to stop the session manager (another program) from respawning it without giving up the normal auto-respawn when Caja just plain crashes.
