### ISSUE TITLE
mate-session-manager-1.22.0 FTBFS

### ISSUE THREAD

**Issue by chris2553** [mate-desktop/mate-session-manager#190]

**Comment by chris2553** [comment]
As per $SUBJECT, I get the following error when building mate-session-manager on a systemd-less system. The error reads:

gsm-systemd.c:432: error: undefined reference to 'sd_pid_get_session'
gsm-systemd.c:438: error: undefined reference to 'sd_uid_get_sessions'
gsm-systemd.c:453: error: undefined reference to 'sd_session_get_state'
gsm-systemd.c:464: error: undefined reference to 'sd_session_get_type'
collect2: error: ld returned 1 exit status

The following patch allows the build to complete, but is only lightly tested.

--- mate-session-manager-1.22.0/mate-session/gsm-systemd.c.orig 2019-03-04 15:14:01.668664101 +0000
+++ mate-session-manager-1.22.0/mate-session/gsm-systemd.c      2019-03-04 15:37:29.260698826 +0000
@@ -429,14 +429,18 @@ gsm_systemd_is_last_session_for_user (Gs
         gboolean is_last_session;
         int ret, i;
 
+#ifdef HAVE_SYSTEMD
         ret = sd_pid_get_session (getpid (), &session);
-
+#else
+       ret = -1;
+#endif
         if (ret != 0) {
                 return FALSE;
         }
 
+#ifdef HAVE_SYSTEMD
         ret = sd_uid_get_sessions (getuid (), FALSE, &sessions);
-
+#endif
         if (ret <= 0) {
                 free (session);
                 return FALSE;
@@ -450,8 +454,9 @@ gsm_systemd_is_last_session_for_user (Gs
                 if (g_strcmp0 (sessions[i], session) == 0)
                         continue;
 
+#ifdef HAVE_SYSTEMD
                 ret = sd_session_get_state (sessions[i], &state);
-
+#endif
                 if (ret != 0)
                         continue;
 
@@ -461,8 +466,9 @@ gsm_systemd_is_last_session_for_user (Gs
                 }
                 free (state);
 
+#ifdef HAVE_SYSTEMD
                 ret = sd_session_get_type (sessions[i], &type);
-
+#endif
                 if (ret != 0)
                         continue;
 
------
Hope this helps.

**Comment by chris2553** [comment]
I've no clue as to why your system has done what it's done to the simple test that I pasted into the message.

**Comment by chris2553** [comment]
This issue seems to have been closed. No idea why, but reopening.

**Comment by texstar** [comment]
On a systemd free system I get:

gsm-systemd.c:432: error: undefined reference to 'sd_pid_get_session'
gsm-systemd.c:438: error: undefined reference to 'sd_uid_get_sessions'
gsm-systemd.c:453: error: undefined reference to 'sd_session_get_state'
gsm-systemd.c:464: error: undefined reference to 'sd_session_get_type'
collect2: error: ld returned 1 exit status

**Comment by chris2553** [comment]
That's because the patch has been wrapped by the github system. It might be my fault - I'm not a regular user of this issue-reporting interface. I'll see if I can find a way to attach the file. I should be able to drag and drop it, but files that end with the suffix .patch are not accepted. Go figure!!

**Comment by chris2553** [comment]
If I understand correctly, I can Drag and drop .txt files so I've fixed up the patch file name.
[mate-session-manager-1.22.0-no-systemd.patch.txt](https://github.com/mate-desktop/mate-session-manager/files/2932438/mate-session-manager-1.22.0-no-systemd.patch.txt)

**Comment by texstar** [comment]
All good here now. Thanks for the patch.

**Comment by chris2553** [comment]
Since raveit63 seems to be giving me a red card, here is the missing data :-)

Expected behaviour
mate-session-manager should build successfully when systemd is not installed on the host.

Actual behaviour
Build fails as reported in my post two days ago.

Steps to reproduce the behaviour
./configure && make

MATE general version
1.22

Package version
1.22.0

Linux Distribution
BLFS

Link to downstream report of your Distribution
None. MATE is not part of BLFS. I build and install it locally (and have done since release 1.16).

**Comment by texstar** [comment]
The 75cc360fcf8b2ee2c54ef748d907c4d07325e863.patch also works for me.

**Comment by chris2553** [comment]
Thanks for the patch, Victor. If I understand correctly, the patch is fixing two separate things. Firstly, it fixes the build on hosts that don't have systemd. Secondly it adds some checking that calls to systemd functions have resulted in values being assigned to variables passed to the function by pointer. That's fine with me, although some projects would prefer those two changes to be in separate patches, but I don't know whether MATE is in that set of projects. Just a heads up.
It seems to me that the patch (and the resulting code) could be much simplified. With your patch, systems without systemd can only ever return FALSE because sd_pid_get_session() will not have been called, so the session variable must still be NULL. Consequently, the rest of the function is effectively dead code because it can never be reached. That means we can make the code much clearer by guarding all the code with "#ifdef HAVE_SYSTEMD" and add a simple, "return FALSE;" in a #else part. As well as adding clarity to the code, surely the compiler will eliminate the call to  gsm_systemd_is_last_session_for_user()  on systems without systemd.
Of course you are the maintainers, so it's your choice but  patch that implements your changes and my additional suggestion is attached.
[mate-session-manager-1.22.0-systemd-fixes.patch.txt](https://github.com/mate-desktop/mate-session-manager/files/2941022/mate-session-manager-1.22.0-systemd-fixes.patch.txt)

**Comment by chris2553** [comment]
Forgot to say that your patch works here too.

**Comment by vkareh** [comment]
@chris2553 - I understand, and what you say makes perfect sense. However, I'm interested in keeping the systemd-specific functions guarded without guarding anything else just to be consistent with the rest of the code. Freeing the memory on those variables should not be necessary for a systemd-free system, but regardless I don't know what those functions may or may not return, so I want to be safe. Call it paranoid coding ;)

As for doing it in separate commits, maybe, but things like `if (session == NULL) { return; }` are definitely part of fixing this issue, and from there to `else { free (session); }` is not that long of a stretch in my opinion.

**Comment by joakim-tjernlund** [comment]
Isn't ret uninitialized if the test if(ret !=0)  when non systemd ?

**Comment by vkareh** [comment]
@joakim-tjernlund - correct, but the code will exit before that, since `session == NULL`

**Comment by joakim-tjernlund** [comment]
ok, so the only effect cold be gcc Warning etc. Good
