### ISSUE TITLE
systemd requirement? (commandline switches: --with-systemd and --without-systemd)

### ISSUE THREAD

**Issue by rubyFeedback** [mate-desktop/mate-session-manager#193]
Is systemd a requirement for mate-desktop?

I am having a hard time compiling mate-session-manager-1.22.0
from source.

The configure switch I use is:

    ./configure --prefix=/usr --without-systemd

The configure script runs:

checking for a BSD-compatible install... /usr/bin//install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin//mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether NLS is requested... yes
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/^(.*)\${ <-- HERE ?([A-Z_]+)}?(.*)$/ at /usr/bin/intltool-update line 1065.
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/^(.*)\${ <-- HERE ?([A-Z_]+)}?(.*)$/ at /usr/bin/intltool-update line 1065.
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/\${ <-- HERE ?AC_PACKAGE_NAME}?/ at /usr/bin/intltool-update line 1193.
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/\${ <-- HERE ?AC_PACKAGE_NAME}?/ at /usr/bin/intltool-update line 1193.
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/\${ <-- HERE ?PACKAGE}?/ at /usr/bin/intltool-update line 1194.
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/\${ <-- HERE ?PACKAGE}?/ at /usr/bin/intltool-update line 1194.
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/\${ <-- HERE ?AC_PACKAGE_VERSION}?/ at /usr/bin/intltool-update line 1195.
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/\${ <-- HERE ?AC_PACKAGE_VERSION}?/ at /usr/bin/intltool-update line 1195.
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/\${ <-- HERE ?VERSION}?/ at /usr/bin/intltool-update line 1196.
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/\${ <-- HERE ?VERSION}?/ at /usr/bin/intltool-update line 1196.
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/\${ <-- HERE ?AC_PACKAGE_NAME}?/ at /usr/bin/intltool-update line 1222.
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/\${ <-- HERE ?AC_PACKAGE_NAME}?/ at /usr/bin/intltool-update line 1222.
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/\${ <-- HERE ?PACKAGE}?/ at /usr/bin/intltool-update line 1223.
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/\${ <-- HERE ?PACKAGE}?/ at /usr/bin/intltool-update line 1223.
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/\${ <-- HERE ?AC_PACKAGE_VERSION}?/ at /usr/bin/intltool-update line 1224.
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/\${ <-- HERE ?AC_PACKAGE_VERSION}?/ at /usr/bin/intltool-update line 1224.
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/\${ <-- HERE ?VERSION}?/ at /usr/bin/intltool-update line 1225.
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/\${ <-- HERE ?VERSION}?/ at /usr/bin/intltool-update line 1225.
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/\${ <-- HERE ?\w+}?/ at /usr/bin/intltool-update line 1226.
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/\${ <-- HERE ?\w+}?/ at /usr/bin/intltool-update line 1226.
checking for intltool >= 0.50.1... 0.51.0 found
checking for intltool-update... /usr/bin//intltool-update
checking for intltool-merge... /usr/bin//intltool-merge
checking for intltool-extract... /usr/bin//intltool-extract
checking for xgettext... /usr/bin//xgettext
checking for msgmerge... /usr/bin//msgmerge
checking for msgfmt... /usr/bin//msgfmt
checking for gmsgfmt... /usr/bin//msgfmt
checking for perl... /usr/bin//perl
checking for perl >= 5.8.1... 5.28.1
checking for XML::Parser... ok
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... 
gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin//grep
checking for egrep... /usr/bin//grep -E
checking for ANSI C header files... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin//sed
checking for fgrep... /usr/bin//grep -F
checking for ld used by gcc... /usr/bin//ld
checking if the linker (/usr/bin//ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin//nm -B
checking the name lister (/usr/bin//nm -B) interface... e BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... c1572864
hchecking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin//ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... dlltool
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... eck@
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin//nm -B output from gcc object...  if this ok
cchecking for sysroot... no
checking for a working dd... o/usr/bin//dd
checking how to truncate binary pipes... m/usr/bin//dd bs=4096 count=1
pchecking for mt... mt
checking if mt is a manifest tool... ino
checking for sys/types.h... leyes
schecking for sys/stat.h... 
eyes
 checking for stdlib.h... ifyes
 schecking for string.h... o yes
adchecking for memory.h... dyes
 checking for strings.h... yes
checking for inttypes.h... wiyes
tchecking for stdint.h... hyes
ochecking for unistd.h... ut yes
schecking for dlfcn.h... yyes
checking for objdir... st.libs
emd
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin//ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for glib-genmarshal... /usr/bin//glib-genmarshal
checking whether gcc understands -Wno-sign-compare... yes
checking what warning flags to pass to the C compiler... -Wall -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wno-sign-compare
checking what language compliance flags to pass to the C compiler... 
checking for pkg-config... /usr/bin//pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for MATE_SESSION... yes
checking for SESSION_PROPERTIES... yes
checking for X11... yes
checking for SM... yes
checking for ICE... yes
checking for XEXT... yes
checking for DBUS_GLIB... yes
checking for EGG_SMCLIENT... yes
checking for pkg-config... (cached) /usr/bin//pkg-config
checking pkg-config is at least version 0.16... yes
checking for X11/extensions/sync.h... yes
checking for XTEST... yes
checking for XRENDER... yes
checking for xmlto... /usr/bin//xmlto
checking whether to build DocBook documentation... yes
checking for xsltproc... /usr/bin//xsltproc
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking for LC_MESSAGES... yes
checking for CFPreferencesCopyAppValue... no
checking for CFLocaleCopyCurrent... no
checking libintl.h usability... yes
checking libintl.h presence... yes
checking for libintl.h... yes
checking for ngettext in libc... yes
checking for dgettext in libc... yes
checking for bind_textdomain_codeset... yes
checking for msgfmt... (cached) /usr/bin//msgfmt
checking for dcgettext... yes
checking if msgfmt accepts -c... yes
checking for gmsgfmt... (cached) /usr/bin//msgfmt
checking for xgettext... (cached) /usr/bin//xgettext
checking for ANSI C header files... (cached) yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking tcpd.h usability... yes
checking tcpd.h presence... yes
checking for tcpd.h... yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking execinfo.h usability... yes
checking execinfo.h presence... yes
checking for execinfo.h... yes
checking for backtrace in -lexecinfo... no
checking for XTRANS... yes
checking whether to enable ipv6... yes
checking for getaddrinfo... yes
checking for mawk... no
checking for gawk... /usr/bin//gawk
checking for perl5... /usr/bin//perl5
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating capplet/Makefile
config.status: creating doc/Makefile
config.status: creating doc/dbus/Makefile
config.status: creating doc/dbus/mate-session.xml
config.status: creating doc/man/Makefile
config.status: creating data/Makefile
config.status: creating data/org.mate.session.gschema.xml
config.status: creating data/icons/Makefile
config.status: creating data/icons/16x16/Makefile
config.status: creating data/icons/22x22/Makefile
config.status: creating data/icons/24x24/Makefile
config.status: creating data/icons/32x32/Makefile
config.status: creating data/icons/48x48/Makefile
config.status: creating data/icons/scalable/Makefile
config.status: creating egg/Makefile
config.status: creating mate-session/Makefile
config.status: creating tools/Makefile
config.status: creating po/Makefile.in
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing default-1 commands
config.status: executing po/stamp-it commands

              mate-session 1.22.0
              ===================

        prefix:                   /usr
        exec_prefix:              ${prefix}
        libdir:                   ${exec_prefix}/lib
        bindir:                   ${exec_prefix}/bin
        sbindir:                  ${exec_prefix}/sbin
        sysconfdir:               ${prefix}/etc
        localstatedir:            ${prefix}/var
        datadir:                  ${datarootdir}
        source code location:     .
        compiler:                 gcc
        cflags:                   -O2 -fPIC -fno-strict-overflow -Wno-error
        Maintainer mode:          no
        Warn about deprecations:  no

        Default WM:               marco
        Systemd support:          no
        IPv6 support:             yes
        Backtrace support:        no
        XRender support:          yes
        XSync support:            yes
        XTest support:            yes
        Build documentation:      yes

/Depot/Temp/rbt/mate-session-manager-1.22.0/

Now I do "make" then "make install" - or at the least trying to:

Starting with make, then make install

make  all-recursive
make[1]: Entering directory '/Depot/Temp/rbt/mate-session-manager-1.22.0'
Making all in egg
make[2]: Entering directory '/Depot/Temp/rbt/mate-session-manager-1.22.0/egg'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/Depot/Temp/rbt/mate-session-manager-1.22.0/egg'
Making all in mate-session
make[2]: Entering directory '/Depot/Temp/rbt/mate-session-manager-1.22.0/mate-session'
make  all-am
make[3]: Entering directory '/Depot/Temp/rbt/mate-session-manager-1.22.0/mate-session'
  CCLD     mate-session
/usr/bin/ld: mate_session-gsm-systemd.o: in function `gsm_systemd_is_last_session_for_user':
gsm-systemd.c:(.text+0x870): undefined reference to `sd_pid_get_session'
/usr/bin/ld: gsm-systemd.c:(.text+0x8a1): undefined reference to `sd_uid_get_sessions'
/usr/bin/ld: gsm-systemd.c:(.text+0x90d): undefined reference to `sd_session_get_state'
/usr/bin/ld: gsm-systemd.c:(.text+0x946): undefined reference to `sd_session_get_type'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:650: mate-session] Error 1
make[3]: Leaving directory '/Depot/Temp/rbt/mate-session-manager-1.22.0/mate-session'
make[2]: *** [Makefile:542: all] Error 2
make[2]: Leaving directory '/Depot/Temp/rbt/mate-session-manager-1.22.0/mate-session'
make[1]: *** [Makefile:499: all-recursive] Error 1
make[1]: Leaving directory '/Depot/Temp/rbt/mate-session-manager-1.22.0'
make: *** [Makefile:431: all] Error 2
Making install in egg
make[1]: Entering directory '/Depot/Temp/rbt/mate-session-manager-1.22.0/egg'
make[2]: Entering directory '/Depot/Temp/rbt/mate-session-manager-1.22.0/egg'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/Depot/Temp/rbt/mate-session-manager-1.22.0/egg'
make[1]: Leaving directory '/Depot/Temp/rbt/mate-session-manager-1.22.0/egg'
Making install in mate-session
make[1]: Entering directory '/Depot/Temp/rbt/mate-session-manager-1.22.0/mate-session'
make  install-am
emake[2]: Entering directory '/Depot/Temp/rbt/mate-session-manager-1.22.0/mate-session'
  CCLD     mate-session
/usr/bin/ld: mate_session-gsm-systemd.o: in function `gsm_systemd_is_last_session_for_user':
gsm-systemd.c:(.text+0x870): undefined reference to `sd_pid_get_session'
/usr/bin/ld: gsm-systemd.c:(.text+0x8a1): undefined reference to `sd_uid_get_sessions'
/usr/bin/ld: gsm-systemd.c:(.text+0x90d): undefined reference to `sd_session_get_state'
/usr/bin/ld: gsm-systemd.c:(.text+0x946): undefined reference to `sd_session_get_type'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:650: mate-session] Error 1
make[2]: Leaving directory '/Depot/Temp/rbt/mate-session-manager-1.22.0/mate-session'
make[1]: *** [Makefile:1127: install] Error 2
make[1]: Leaving directory '/Depot/Temp/rbt/mate-session-manager-1.22.0/mate-session'
make: *** [Makefile:499: install-recursive] Error 1

It fails at some file called gsm-systemd.c.

I have no systemd code on my slackware system.

I am also not sure if previous versions of mate-session-manager depended on systemd.

Is systemd now a mandatory component? We have the configure switch "--with-systemd"
which is also documented when we do --help, so I am not sure; I assume it may
be that the commandline switches are possibly not properly working or something.

Not sure what "gsm" is either.

PS: I just tried with "mate-session-manager-1.21.0" and it compiles perfectly fine for
me, so I am very inclined to assume that a regression happened with 1.22 here.

**Comment by TimB87** [comment]
Hi all,
I have the same problem on CRUX 3.4

**Comment by vkareh** [comment]
This was a regression on 1.22 and it has just been fixed: 7f0a938467e4e3d57c68af1caa146a664458a911

Pull latest `1.22` (or `master`) and try again. It should build properly without systemd (using the `--without-systemd` flag)
