### ISSUE TITLE
Altering Marco in a panel Menu editor disables the window manager from starting

### ISSUE THREAD

**Issue by AKSoo** [mate-desktop/mate-session-manager#221]
#### Expected behaviour
MATE's startup should not be affected by changes made in a panel Menu editor. MATE should at least fail graceful and/or report the problem to the user.

#### Actual behaviour
MATE fails to start marco for no apparent reason or errors logged.

#### Steps to reproduce the behaviour
1. Open Menu editor (Mozo) on any panel
2. Delete Applications/Other/Marco
3. `Hidden=true` is appended to ~/.local/share/applications/marco.desktop
4. On next session login, marco fails to start, resulting in a crippled DE.

#### MATE general version
1.22.2

#### Package version
1.22.1

#### Linux Distribution
Arch Linux

This is a more detailed report that explains #21

**Comment by raveit65** [comment]
Why did you do that and break your session?
Everything works well without editing or deleting this file.

**Comment by AKSoo** [comment]
And users are expected to know they can break their DE while editing the goddamn panel menu with Mozo? (which can happen accidentally, since there's no confirmation or warning)

While this is more of Mozo issue (see mate-desktop/mozo#64), this error should not happen either.
