### ISSUE TITLE
How to start mate desktop environment on KNOPPIX_V8.6-2019-08-08

### ISSUE THREAD

**Issue by JanuszChmiel** [mate-desktop/mate-session-manager#224]
#### Expected behaviour
mate-session
command should normally initiate mate desktop environment, since no display manager run at The background because I use init 2 command to kill LXDE session of Knoppix.

#### Actual behaviour
mate-session
command produces some strange error with number related to some part of mate-session C source code and warning word. I Am very sorry, that I do not have The exact error message.

#### Steps to reproduce the behaviour
download
KNOPPIX_V8.6-2019-08-08 from
ftp://ftp.uni-kl.de/pub/linux/knoppix-dvd/KNOPPIX_V8.6-2019-08-08-EN.iso
accept The default choice of Knoppix while booting it from some compatible bootable media. 
When Lxde sstart, run
lxdeterminal
sudo su
init 2
apt update
apt-get install task-mate-desktop
When all installation steps will be finished, type
mate-session.
Error will occur very soon after running mate-session.

When you will try to type
xinit mate-session
Mate will not allow user to use CTRL+ALT+D to display desktop icons by using Caja.
And Speech-dispatcher will refuse to send data to Espeak engine. Sound volume monitor will work so multimedia sound keys will increase or decrease The volume and system will produce short gong signal when volume will be increased or decreased by using multimedia keys on The multimedia keyboard.

#### MATE general version
Latest available for Debian buster AMD 64.

#### Linux Distribution
KNOPPIX_V8.6-2019-08-08

#### Link to downstream report of your Distribution
None.
I would really like to use Mate with Knoppix, because Mr professor Knopper have specially preconfigured The system and The kernel wwhile compiling it so ALSA sound server is being used instead of Pulseaudio. I can not simply remove Pulseaudio from Ubuntu Mate, because removing it causes other crucial package to be removed, including mate-core.
If somebody would have some little time to analyse The issue, it would be amazing.
There are no better free voice for Czech on Linux than Espeak. Mbrola synthesizer do not produce background sounds when Pulseaudio is being used, but speech quality is not good related to very short language recorded database.
Mate is better than LXDE, because desktop, panel and all of its official build in apps are really fullyaccessible for Orca users. This is not true for many other desktops based on GTK.
Thank you very much for yours time and for yours help.
Sure, I Am ready to test and do not forget on excellent features of Knoppix. You can combine live system with overlay file or with standalone big partition. So it is very easy to test mate even on The systems, which have less than 4 GB of RAM.

**Comment by thomas-t-w** [comment]
I think that distro might use consolekit. CAn you confirm this? It might have to do with some conflicts between logind and consolekit because mate is built against logind in dEbian. Can someone else comment here. I think this sounds like a downstream issue so maybe closed here.

**Comment by JanuszChmiel** [comment]
I AM very sorry that I have intruded you. I did not deeply analysed C language source code of Mate desktop to determine this.
Do you think, that I can run mate-session even it was not been intended to run in conjunction with consolekit daemon?
When I will pay attention on login empty sub window and if I will not accidentally close it, all routines work smoothly.
You can close this issue. Debian enforces using Pulseaudio and also Ubuntu Mate.
And mate-volume monitor work perfectly with mate-session on Knoppix even ALSA sound server is being used.
Thank you very much for yours explanation related to console kit daemon.
