### ISSUE TITLE
The "Fix timeout with gnome-keyring 3.34" is actually 3.31.91

### ISSUE THREAD

**Issue by joakim-tjernlund** [mate-desktop/mate-session-manager#226]
Gentoo just got  gnome-base/gnome-keyring-3.31.91 in stable and the above tmo
is hitting MATE.

Perhaps a new release sooner rather than later of mate-session-manager-1.22/1.23 ?

**Comment by raveit65** [comment]
mate-session-manager-1.22.3 is released.
