### ISSUE TITLE
Changes in startup items command field don't get remembered

### ISSUE THREAD

**Issue by rodoviario** [mate-desktop/mate-session-manager#235]
#### Expected behaviour
If a user wants to change the command excecuted by an item of the list, it should be able to press Edit, modify the command field (or go trough "navigate" and select a new excecutable), and save it

#### Actual behaviour
After reboot the item on the list looks unmodified

#### Steps to reproduce the behaviour
1. Open mate-sesion-manager
2. Scroll to some item (ie: Joplin)
3. Press "Edit"
4. Edit text in field labeled "Command:"
5. Click "Save"
6. Reboot 
7. The new command wont excecute
8. Go to 1, 2 and 3 to see that it hasn't changed

#### MATE general version
1.22

#### Package version
1.22.2-1-tricia

#### Linux Distribution
Linux Mint 19.3 Tricia 64-bits
Mate
#### Link to downstream report of your Distribution
According to the[ Linux Mint Troubleshooting guide](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/where.html)
_Bugs which affect MATE or one of its components should be reported on the MATE Github site._

**Comment by raveit65** [comment]
> Link to downstream report of your Distribution

> According to the Linux Mint Troubleshooting guide
> Bugs which affect MATE or one of its components should be reported on the MATE Github site.

This is a MATE repo and not owned by Linuxmint.
According MATE guidelines this is not acceptable.

**Comment by rodoviario** [comment]
Sorry if I offend you in any way. I'm mate lover since ever. Just wanted to report a bug, and when found the "link to the downstream report" part, wanted to report in my distro, but was unable to do it there, acording to their policy. I also understand the part you mention of the MATE guidelines which prevents reporting directly to upstream either. I wasn't aware of the incompatibility of policies and didn't research further because I was with the wrong idea that linuxmint and mate where friends, friendliy or at least cooperative between each other after reading on the same page that "_MATE is co-developed by Linux Mint._"... which misleaded me. So from now on, as an user (regarding to mate + linux mint) I know that is a waste of everybodies time to try to contribute reporting bugs and that I am on my own.

**Comment by raveit65** [comment]
Closed by accidental. I am sure Linux Mint head Clement Lefebvre or other Linuxmint guys will help you. https://github.com/orgs/mate-desktop/people/clefebvre Because they all received notifications from this repo.

But i do not agree with their weird guide because they speak about other peoples time to work on reports!

PS: MATE 1.22 is EOL since 1.24 is released!

**Comment by rodoviario** [comment]
Glad to hear that, thanks!

**Comment by raveit65** [comment]
See #156 (comment)
#156 (comment)
#272

**Comment by raveit65** [comment]
Fixed for master and stable branch.
https://github.com/mate-desktop/mate-session-manager/pull/279
https://github.com/mate-desktop/mate-session-manager/pull/274
