### ISSUE TITLE
[mate-session-properties] [1.24.0] Enable/Disable flag is not saved

### ISSUE THREAD

**Issue by vinzodip** [mate-desktop/mate-session-manager#240]
#### Expected behaviour
The flag should be saved.

#### Actual behaviour
The flag was not saved.

#### Steps to reproduce the behaviour
Open mate-session-properties and enable or disable a flag of any program you want.
Close and re-open mate-session-properties.
Check the flag previously changed.

#### MATE general version
1.24.0

#### Linux Distribution
Ubuntu Mate 20.04

**Comment by raveit65** [comment]
See #156 (comment)
#156 (comment)
https://github.com/mate-desktop/mate-session-manager/pull/272

**Comment by raveit65** [comment]
Fixed for master and stable branch.
https://github.com/mate-desktop/mate-session-manager/pull/279
https://github.com/mate-desktop/mate-session-manager/pull/274
