### ISSUE TITLE
Notification area item just not working dont show any icons on Ubuntu mate 20.04

### ISSUE THREAD

**Issue by ruthan** [mate-desktop/mate-session-manager#246]
I its not working for long time, its replaced by A unified apple contanting all of indicars - applet, so it should be removed from options menu, because its dead.
  Otherwise spaces between icons for A unified apple contanting all of indicars  is too wide, its eating too much of my Start panel..

**Comment by raveit65** [comment]
1. Notification area is part of mate-panel
2. Ubuntu-Mate doesn't use our notification-area. They use their own indicators. 
Please file out a report at Ubuntu launchpad, or ask for help at Ubuntu-Mate https://ubuntu-mate.org/support/
