### ISSUE TITLE
[Mate Session properties] Pulseaudio doesn't disable

### ISSUE THREAD

**Issue by SimonBenito** [mate-desktop/mate-session-manager#259]
#### Expected behaviour
When you uncheck pulse audio sound system ("Sistema de sonido PulseAudio" in my language), next time you restart your computer it should be disabled.
It's my best guess  that it's a mate's issue on .desktop files.

#### Actual behaviour
It's enabled anyways

#### Steps to reproduce the behaviour
Open mate session properties, uncheck pulseaudio, close and restart

#### MATE general version
1.24.0

#### Package version
apt list mate-session-manager  -a
Listando... Hecho
mate-session-manager/focal,now 1.24.0-2ubuntu1 amd64 [instalado]

#### Linux Distribution
Linux Mint 20

#### Link to downstream report of your Distribution
I'm sorry, I don't understand what I have to say here . Tell me where are the instructions and I'll answer

**Comment by raveit65** [comment]
Pulseaudio service will be started before mate session was started, mostly by the login manager.
You need to mask pulsaudio service if you don't want it.
```
systemctl --user mask pulseaudio.service
systemctl --user mask pulseaudio.socket
```

**Comment by raveit65** [comment]
Fixed for master and stable branch.
https://github.com/mate-desktop/mate-session-manager/pull/279
https://github.com/mate-desktop/mate-session-manager/pull/274
