### ISSUE TITLE
XDG autostart enable/disable functionality not compatible with XFCE

### ISSUE THREAD

**Issue by sunweaver** [mate-desktop/mate-session-manager#260]
#### Expected behaviour

.desktop files in XDG autostart locations with the key Hidden= set to true are visible in the mate-session-properties dialog and can be (re-)enabled there, other desktop envs use Hidden=true|false to enable/disable startup applications. See also #134 for how to hide startup applications from the mate-session-properties dialog entirely.

#### Actual behaviour

Currently, mate-session-properties uses a MATE specific flag for disabling XDG autostart applications (X-MATE-Autostart-enabled=false). This boolean switch is not portable to other desktop environments. Please consider using the Hidden= key instead.

The explicit problem I have is this:

  * disable autostart of an application in XFCE -> this sets Hidden=true in the .desktop file
  * I cannot re-enable autostart for this application in MATE

Other way around:

  * I disable autostart of an application in MATE -> this sets X-MATE-Autostart-enabled=false
  * the application still autostarts in XFCE

I haven't tested other desktop envs. Let me know, if I should.

The context is: Ayatana Indicators. The system indicators are services usable across different desktop envs. At some point, they should be controllable via systemd user services (on systems having systemd). On systems without systemd / as of today, XDG autostart is used to launch the system indicator services. It should be possible to enable/disable those services cross-desktop-env.

#### Steps to reproduce the behaviour

Install MATE and XFCE on the same machine. Disable/enable XDG autostarted application using mate-session-properties and XFCE's xfce4-session-settings and switch between desktop environments

#### MATE general version

1.20 / 1.24

#### Package version

1.20

#### Linux Distribution

Debian/Ubuntu

#### Link to downstream report of your Distribution

none

**Comment by joakim-tjernlund** [comment]
Yes please, I got the same problem and cannot disable autostart apps using MATE.
The problem is exactly as described above, one must use Hidden property.

**Comment by raveit65** [comment]
Pulseaudio service will be started before mate session was started, mostly by the login manager.
You need to mask pulsaudio service if you don't want it.
```
systemctl --user mask pulseaudio.service
systemctl --user mask pulseaudio.socket
```

**Comment by raveit65** [comment]
> I got the same problem and cannot disable autostart apps using MATE

See, 
https://github.com/mate-desktop/mate-session-manager/issues/156#issuecomment-808731386
https://github.com/mate-desktop/mate-session-manager/issues/156#issuecomment-808893461
https://github.com/mate-desktop/mate-session-manager/pull/272
