### ISSUE TITLE
Logind does not appear to be fully supported

### ISSUE THREAD

**Issue by Firstyear** [mate-desktop/mate-session-manager#27]
logind provides a number of functions to help interact with sessions that are active on the machine. the tool to interact with these is loginctl.

At this time, the loginctl tools do not correctly interact with MATE. For example

loginctl lock-sessions should cause the screensaver and lock to be activated on all desktops. in Mate however, this does not occur. Conversely, loginctl unlock-session [seat number] should unlock the screensaver. This also does not occur.

**Comment by monsta** [comment]
What are the benefits of supporting this ```loginctl``` tool? Well, except for having a cool way to lock/unlock sessions from command line :smile:

**Comment by monsta** [comment]
@Firstyear: this issue seems to be fixed by https://github.com/mate-desktop/mate-screensaver/pull/80 (even the first commit, https://github.com/paravoid/mate-screensaver/commit/2eeb0c69c122b62073b2626d9ede5bff5ad8bc20, is enough). Please test if it works for you.
