### ISSUE TITLE
screen not locked after suspend

### ISSUE THREAD

**Issue by MASHtm** [mate-desktop/mate-session-manager#277]
#### Expected behaviour
I'm on Fedora 33. And until the update to mate-session-manager 1.24.2 the screen was locked properly after resuming from suspend. My mate-screensaver is set to lock on blank.

#### Actual behaviour
Screen is not locked and the journal contains:
mate-session[9518]: WARNING: Couldn't lock screen: Failed to execute child process “mate-screensaver-command” (No such file or directory)

#### Steps to reproduce the behaviour
I assume this happens on all Fedora 33 and other distributions as well after updating mate-session-manager containing
https://github.com/mate-desktop/mate-session-manager/commit/071933646ef80fff6295b581376d018ba8ddc39a

#### MATE general version
1.24.1
mate-desktop-1.24.1-3.fc33.x86_64

#### Package version
mate-session-manager-1.24.2-2.fc33.x86_64

#### Linux Distribution
Fedora 33

#### Link to bugreport of your Distribution (requirement)
I report this only here because it looks like something got wrong in
https://github.com/mate-desktop/mate-session-manager/commit/071933646ef80fff6295b581376d018ba8ddc39a
and mate-screensaver-command is not found while it is installed:
```
# which mate-screensaver-command 
/usr/bin/mate-screensaver-command
```
and working as expected when called with "--lock".

**Comment by MASHtm** [comment]
Sorry, I linked to the commit for master tree. 1.24 commit was
https://github.com/mate-desktop/mate-session-manager/commit/81b6185eb3d47cba4d8f1232556e176b9f810015

And after I rebuilt the package with this commit reverted everything works as expected again. My guess is that g_spawn_command_line_async() uses PATH (which is correctly set on the running daemon) and g_spawn_async() does not.

**Comment by raveit65** [comment]
^^^^^^ @rbuj 
We have a problem with your commit.

**Comment by raveit65** [comment]
@MASHtm 
Does the issue exists with suspend_to_ram or suspend_to_disk in f33?

**Comment by MASHtm** [comment]
I only use "Suspend" and not "Hibernate" to use MATE's own terms. So suspend_to_ram.
