### ISSUE TITLE
Excess CPU use after commit f56f8cd

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/mate-session-manager#281]
#### Expected behaviour
Near-zero CPU use by system at idle

#### Actual behaviour
10-20% CPU use across all 8 threads on AMD Bulldozer with some default services (from GNOME and Cinnamon installs) disabled, one or more custom jobs modifying normal MATE jobs, and one or more custom startup jobs (conky in my case)

#### Steps to reproduce the behaviour
Install m-s-m from today's git master (1.24.3 not tested but probably same problem), install Cinnamon or GNOME, and disable some non-MATE startup jobs. Also (in case this is the culprit) disable network-manager-applet and create a new startup job for it with `nm-applet --indicator` and create one or more custom startup jops as on my system. This will work fine with older versions of mate-session-manager but after 
https://github.com/mate-desktop/mate-session-manager/commit/f56f8cd63d330e576aeabd09a0600a8da2e02392
Follow freedesktop guidelines to disable autorun using Hidden key 
you will see excessive CPU use

#### MATE general version
1.25

#### Package version
locally compiled from git master as of 4-22-2021

#### Linux Distribution
Debian Unstable

#### Link to bugreport of your Distribution (requirement)
None as this is a locally compiled package

**Comment by raveit65** [comment]
Which process does have a high CPU load?

**Comment by raveit65** [comment]
I can't reproduce a high cpu load with `nm-applet --indicator` as a new start job.
Neither mate-session or nm-applet processes produce a high cpu load here.
Everything work as normal with mentioned commit.
Is your issue reproducible with a fresh new user account?

**Comment by lukefromdc** [comment]
Highest CPU use I saw got credited to xorg for some reason. Possibly something further down trying to repeatedly start and in the process have to try to open a window, only to be killed prior to ahowing up.

**Comment by lukefromdc** [comment]
On the road now,but I DID notice that my previous list of enabled and diaabled startup jobs was ignores and I had to redo most of it on first run(during initial testing).

I do NOT want to reset all of dconf due to the level of customization elsewhere in my setup

A different username is the way I can test that when I am back home

**Comment by lukefromdc** [comment]
Found the culprit: I had xscreensaver uninstalled but not xscreensaver-data, and still had that listed as a startup jop. With xscreensaver not installed, the session manager apparently kept trying to start it.  Apparently  the previous code tolerated this but the new code does not. Closing
