### ISSUE TITLE
Css for lock screen

### ISSUE THREAD

**Issue by luigifab** [mate-desktop/mate-session-manager#295]
This is a question, how I can set styles (from my theme) for the lock screen in Mate 1.26?
The gtk-inspector doesn't start, so I can't find css class names.

![lock-screen](https://user-images.githubusercontent.com/31816829/147411459-6b2679a9-0ab6-4421-89ab-9c49715ca78f.png)

**Comment by mbkma** [comment]
screensaver-preferences->Background Picture for lock screen

**Comment by luigifab** [comment]
2x yes, but I want to remove the border around the window.
To do that I need a css class name or an identifier.
I haven't found the css structure of this screen.

**Comment by rbuj** [comment]
You can override the css as follows:
```
mkdir -p ~/.config/gtk-3.0
cat << EOF >> ~/.config/gtk-3.0/gtk.css
.lock-dialog frame {
    border-radius: 0px;
    border-style: none;
    border-width: 0px;
}
EOF
```
