### ISSUE TITLE
session manager bug ubuntu-mate ubuntu 22.04 

### ISSUE THREAD

**Issue by krcox01** [mate-desktop/mate-session-manager#300]
#### Expected behaviour

.........expect to see all installed desktop environments in session manager list (lightdm)

#### Actual behaviour

.........there are multiple desktop environments half the list is below the bottom of the screen and the list does not scroll
.........also, there are several double entries of some of the desktop environment names

#### Steps to reproduce the behaviour

........added more than eight desktop environments some using tasksel 
........(added all tasksel available desktop environments)... 
........perhaps this caused some of the multiple desktop environment names listed double entries

#### MATE general version

........Ubuntu 22.04.1

#### Package version
?

#### Linux Distribution
........Ubuntu-MATE

#### Link to bugreport of your Distribution (requirement)
?

**Comment by zhuyaliang** [comment]
Please report the issue here  [lightdm](https://github.com/canonical/lightdm)

**Comment by zhuyaliang** [comment]
@krcox01 Can I close the issue ？

**Comment by lukefromdc** [comment]
Closing as we do not maintain lightdm, nothing we can do here.
