### ISSUE TITLE
Missing 'dock' requirement

### ISSUE THREAD

**Issue by rezso** [mate-desktop/mate-session-manager#301]
The org.mate.session.gschema.xml.in contains 'windowmanager', 'panel', 'filemanager', 'dock' as required default components.
But the session manager not founds any 'dock' component in the core mate installation.
Where is the 'dock' component?

**Comment by lukefromdc** [comment]
Pretty sure that was added to permit a user to add a dock to their layout, then have mate-session-manager start it with the session, Note that a "required component" is only actually required if given a program name. Remove "caja" for instance and not replace it, and no filemanager is required in sessions started with that setting. That is useful when debugging caja by running the main instance from terminal(other way is run caja as root from terminal).

**Comment by raveit65** [comment]
This was added by Ubuntu-Mate maintainer (@flexiondotorg)  some years ago. The dock exists only in Ubuntu-Mate as far as i know.
