### ISSUE TITLE
No lock-screen after suspend/hibernate

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/mate-session-manager#308]
#### Expected behaviour
Working lock-screen after suspend/hibernate

#### Actual behaviour
Session isn't locked after suspend/hibernate

#### Steps to reproduce the behaviour
Install Mate and mate-session-manager from master
Suspend/hibernate the system
resume the system

#### MATE general version

> 1.27.0
#### Package version
> 1.27.0

#### Linux Distribution
Fedara and all other

#### Link to bugreport of your Distribution (requirement)
1.27 isn't released

Removing this commit fixes the issue
https://github.com/mate-desktop/mate-session-manager/commit/92c9a82105b222a934e994a87738673351ad33ee

**Comment by zhuyaliang** [comment]
@raveit65 
There are two shared directories in your system : ```/usr/local/share/``` and ```/usr/share```
This results in you having two ```gschemas.compiled``` files
```/usr/local/share/glib-2.0/schemas/gschemas.compiled```
```/usr/share/glib-2.0/schemas/gschemas.compiled```
Attempting to remove ```/usr/local/share/glib-2.0/schemas/gschemas. compiled``` can solve the problem
I don't know if this is considered a bug in glib

**Comment by raveit65** [comment]
Removing `/usr/local/share/glib-2.0/schemas/gschemas.compiled` was really a bad idea. gdm login-manager didn't come up after a reboot.
Restoring `gschemas.compiled` fixes the new problem.
So, removing those files isn't the solution and i don't think that creating those files with a package installation is a glib bug.

**Comment by lukefromdc** [comment]
This is probably happening from local builds using /usr/local, which means `gschemas.compiled` must be being looked for only /usr/local/share/glib-2.0/schemas/

**Comment by zhuyaliang** [comment]
```g_settings_schema_source_lookup``` looks for ```gschemas.compiled``` in multiple directories and retrieves the ```schema``` from it.If no ```schema id``` is found in ```gschemas.compiled```, it means failure
```
openat(AT_FDCWD, "/usr/share/glib-2.0/schemas/gschemas.compiled", O_RDONLY|O_CLOEXEC) 
openat(AT_FDCWD, "/usr/local/share/glib-2.0/schemas/gschemas.compiled", O_RDONLY|O_CLOEXEC)
openat(AT_FDCWD, "/var/lib/flatpak/exports/share/glib-2.0/schemas/gschemas.compiled", O_RDONLY|O_CLOEXEC) 
openat(AT_FDCWD, "/home/mate/.local/share/flatpak/exports/share/glib-2.0/schemas/gschemas.compiled", O_RDONLY|O_CLOEXEC)
openat(AT_FDCWD, "/home/mate/.local/share/glib-2.0/schemas/gschemas.compiled", O_RDONLY|O_CLOEXEC)
```

**Comment by raveit65** [comment]
Every dnf/rpm/apt package installation with gsettings keys create or updated /usr/share/glib-2.0/schemas/gschemas.compiled.
So this file can't be removed. GDM doesn't work with it.
Why not simple reverting the culprit commit https://github.com/mate-desktop/mate-session-manager/commit/92c9a82105b222a934e994a87738673351ad33ee
It's very simple to reproduce which commit causes the problem.
Every suspend-on-lid-close from notebooks will be broken when we release this commit.

**Comment by raveit65** [comment]
I can confirm that removing `/usr/local/share/glib-2.0/schemas/gschemas.compiled` brings back the lock-screen after suspend/hibernate.
But i can't recall that this was ever a problem without https://github.com/mate-desktop/mate-session-manager/commit/92c9a82105b222a934e994a87738673351ad33ee
And i want to avoid to get bugreport in my mail box when users use `/usr/local/' for installations with gsettings keys.
Well, i can revert that for fedora for my own :)

**Comment by zhuyaliang** [comment]
I don't mind revert [92c9a821](https://github.com/mate-desktop/mate-session-manager/commit/92c9a82105b222a934e994a87738673351ad33ee) commit I just want to explain why there were issues with this scommit

**Comment by raveit65** [comment]
More testings shows that the issue is clear reproducible.
- installing atril to `/usr/local`  --> lock-screen failed after susbend/hipernate
- removing https://github.com/mate-desktop/mate-session-manager/commit/92c9a82105b222a934e994a87738673351ad33ee and installing atril to `/usr/local`  --> lock-screen works well after suspend/hibernate.
