### ISSUE TITLE
MATE sometimes doesn't start

### ISSUE THREAD

**Issue by equeim** [mate-desktop/mate-session-manager#54]
I launch X with startx command. Sometimes there is only black screen with busy cursor. Gentoo with consolekit, MATE 1.8. Also I had this problem on Arch with systemd.
startx log with 'mate-session --debug':
http://pastebin.com/QqJ9LD8Q

**Comment by monsta** [comment]
Does it still happen in 1.10?

**Comment by monsta** [comment]
If there won't be any more feedback I'm closing this as fixed.
