### ISSUE TITLE
Switch user does not lock screen

### ISSUE THREAD

**Issue by tagatac** [mate-desktop/mate-session-manager#60]
**Steps to Reproduce:**
1. Log in as user1, where user1 has password-protected login.
2. Click "Log Out" from mintMenu, and before the timer expires click "Switch User".
3. Log in as user2.
4. Log out as user2.

**Expected Results:**
user1 needs to unlock the screen.

**Actual Results:**
user1 is still logged in and his desktop is shown on screen.

mate-session 1.8.1

**Comment by cosimosimeoneTR** [comment]
Hi there guys!
Don't know why this -and realted issue- has been closed, since a fresh new install Debian 8.5 install from official iso still has this problem.

Thanks for help :-)

**Comment by monsta** [comment]
Debian 8 has very outdated MATE version - 1.8.
