### ISSUE TITLE
mate-session crashes

### ISSUE THREAD

**Issue by ildar** [mate-desktop/mate-session-manager#69]
from .xsession-errors :
> process 1821: arguments to dbus_message_new_method_call() were incorrect, assertion "_dbus_check_is_valid_path (path)" failed in file dbus-message.c line 1266.
> This is normally a bug in some application using the D-Bus library.
>   D-Bus not built with -rdynamic so unable to print a backtrace
> mate-session[1821]: ******************* START ********************************
> mate-session[1821]: Frame 0: /usr/bin/mate-session() [0x8060454]
> mate-session[1821]: Frame 1: /usr/bin/mate-session() [0x80608d9]
> mate-session[1821]: Frame 2: linux-gate.so.1(__kernel_sigreturn+0) [0xb76f2400]
> mate-session[1821]: Frame 3: /lib/libc.so.6(gsignal+0x45) [0xb6b600c5]
> mate-session[1821]: Frame 4: /lib/libc.so.6(abort+0x143) [0xb6b618b3]
> mate-session[1821]: Frame 5: /lib/libdbus-1.so.3(+0x35225) [0xb6e7e225]
> mate-session[1821]: Frame 6: /lib/libdbus-1.so.3(+0x2a3d1) [0xb6e733d1]
> mate-session[1821]: Frame 7: /lib/libdbus-1.so.3(dbus_message_new_method_call+0x126) [0xb6e62736]
> mate-session[1821]: Frame 8: /usr/bin/mate-session() [0x805a0c0]
> mate-session[1821]: Frame 9: /usr/lib/libgobject-2.0.so.0(g_cclosure_marshal_VOID__UINT+0x9a) [0xb6df787a]
> mate-session[1821]: Frame 10: /usr/lib/libgobject-2.0.so.0(g_closure_invoke+0x186) [0xb6df5566]
> mate-session[1821]: Frame 11: /usr/lib/libgobject-2.0.so.0(+0x207b5) [0xb6e077b5]
> mate-session[1821]: Frame 12: /usr/lib/libgobject-2.0.so.0(g_signal_emit_valist+0xebd) [0xb6e0f91d]
> mate-session[1821]: Frame 13: /usr/lib/libgobject-2.0.so.0(g_signal_emit+0x33) [0xb6e0faf3]
> mate-session[1821]: Frame 14: /usr/bin/mate-session() [0x805ef73]
> mate-session[1821]: Frame 15: /usr/bin/mate-session() [0x805efec]
> mate-session[1821]: Frame 16: /usr/bin/mate-session() [0x805f090]
> mate-session[1821]: Frame 17: /usr/bin/mate-session() [0x805e58d]
> mate-session[1821]: Frame 18: /usr/lib/libgdk-x11-2.0.so.0(+0x57a3e) [0xb709ca3e]
> mate-session[1821]: Frame 19: /usr/lib/libgdk-x11-2.0.so.0(+0x5927b) [0xb709e27b]
> mate-session[1821]: Frame 20: /usr/lib/libgdk-x11-2.0.so.0(+0x5932d) [0xb709e32d]
> mate-session[1821]: Frame 21: /lib/libglib-2.0.so.0(g_main_context_dispatch+0x143) [0xb6cffff3]
> mate-session[1821]: Frame 22: /lib/libglib-2.0.so.0(+0x4b390) [0xb6d00390]
> mate-session[1821]: Frame 23: /lib/libglib-2.0.so.0(g_main_loop_run+0x7b) [0xb6d0086b]
> mate-session[1821]: Frame 24: /usr/lib/libgtk-x11-2.0.so.0(gtk_main+0xb0) [0xb7230e70]
> mate-session[1821]: Frame 25: /usr/bin/mate-session() [0x804fbd7]
> mate-session[1821]: Frame 26: /lib/libc.so.6(__libc_start_main+0xf5) [0xb6b4b605]
> mate-session[1821]: Frame 27: /usr/bin/mate-session() [0x8050225]
> mate-session[1821]: ******************* END **********************************

version 1.6.1-alt1_3

**Comment by monsta** [comment]
MATE 1.6.x isn't supported now, can you try 1.8.x?

**Comment by monsta** [comment]
@stefano-k @flexiondotorg this can be closed due to unsupported version and lack of response.
