### ISSUE TITLE
loggout buttons are not described to gnome-orca on loggout or shutdown prompt

### ISSUE THREAD

**Issue by mhussaincov** [mate-desktop/mate-session-manager#70]
when you click loggout, orca does not tell me that i am on the loggout button the dyalog box is completely inaccessible.
how ever when I press the enter key, it does logg me out.

**Comment by monsta** [comment]
@coffeeking: can you please confirm or refute this (for both GTK+ builds if possible)?

**Comment by coffeeking** [comment]
hi
I'll get right on it. But I seem to remember both the log out and shut 
down buttons being usable on gtk2 and gtk3 builds. Or does the reporter 
mean once logged out, they're no longer accessible? I have had an issue 
where the shutdown and logout dialog isn't immediately focused, but this 
can be fixed by pressing control+alt+tab, so it's minor. I'd still like 
to figure out what's causing it but that's another issue. This is also 
intermittent, sometimes it happens and sometimes it doesn't.

Thanks
Kendell clark

**Comment by monsta** [comment]
Yes, I get the focus issue sometimes - usually when I press Ctrl-Alt-Del to invoke the shutdown dialog, rather than using the menu. It's something in Marco I think.

**Comment by mhussaincov** [comment]
this issue no longer iffects me, I believe I had posted this as a bugg
quite some time ago.
not currently at a *nix machine to dubble check, when I do get to it
i'll dubble check to be sure.
thanks,
Majid

On 08/01/2016, monsta <notifications@github.com> wrote:
> Yes, I get the focus issue sometimes - usually when I press Ctrl-Alt-Del to
> invoke the shutdown dialog, rather than using the menu. It's something in
> Marco I think.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mate-desktop/mate-session-manager/issues/70#issuecomment-169957335


-- 
kind regards,
Majid Hussain

**Comment by monsta** [comment]
So... does it still happen?

**Comment by coffeeking** [comment]
hi
Not in mate 1.12 on latest sonar, which is manjaro with speech. The 
logout buttons are said properly with orca.
Thanks
Kendell Clark

**Comment by monsta** [comment]
Ok, closing it then.

**Comment by mhussaincov** [comment]
heya,
yes all is functioning as expected now, loggout and shutdown buttons
are being discribed :) thanks to the person who fixed that!
what is happening about the gksu issue and no accessibility when
running apps as root?
tar,
Majid Hussain

**Comment by coffeeking** [comment]
hi
I'd love to know this as well. It did work in the gtk3 port at one
point, but then it broke. Gnome seems to have some way of getting around
this, but this is a critical issue and needs to be fixed because it
makes it impossible to run partition rescue tools such as gparted when
in mate.
Thanks
Kendell Clark


mhussaincov wrote:
> heya,
> yes all is functioning as expected now, loggout and shutdown buttons
> are being discribed :) thanks to the person who fixed that!
> what is happening about the gksu issue and no accessibility when
> running apps as root?
> tar,
> Majid Hussain
>

**Comment by coffeeking** [comment]
hi
One other issue I've noticed, I know this is a separate issue, but I'm
not sure what component to file the issue against, is this. If you have
the size option as the first thing after the icon's description in the
"display" tab of caja, and the file you land on has a number as the last
character of it's extension, eg mp3, mp4, there's no space between that
and the size. So orca will say for example, test.mp33.0 miB mp3 audio.
I'm not sure if this is an orca issue or a mate one. Would anyone mind
looking into this once I file an issue? Which component would this issue
be filed for?
Thanks
Kendell Clark


kendell clark wrote:
> hi
> I'd love to know this as well. It did work in the gtk3 port at one
> point, but then it broke. Gnome seems to have some way of getting around
> this, but this is a critical issue and needs to be fixed because it
> makes it impossible to run partition rescue tools such as gparted when
> in mate.
> Thanks
> Kendell Clark
>
>
> mhussaincov wrote:
>> heya,
>> yes all is functioning as expected now, loggout and shutdown buttons
>> are being discribed :) thanks to the person who fixed that!
>> what is happening about the gksu issue and no accessibility when
>> running apps as root?
>> tar,
>> Majid Hussain
>>

**Comment by monsta** [comment]
Caja is here: https://github.com/mate-desktop/caja/

Not sure about gksu issue - is there an existing report about that?

**Comment by monsta** [comment]
Though maybe it's better to ask orca developers first. The point is that extension and size are in different columns of GtkTreeView, so I think that orca should recognize that...

**Comment by coffeeking** [comment]
hi
I'm not sure. I believe so, but I'll check and file one if not. The
issue is basically that when running apps with gksu, orca cannot get at
them to read their contents. When launching them with pkexec, which uses
policy kit, this usually but not always works. Caja I believe is hard
coded to use gksu when opening folders or running apps as admin, at
least in the gtk2 port. I'm not sure about gtk3.
Thanks
Kendell Clark


monsta wrote:

**Comment by coffeeking** [comment]
hi
Good point. I'll mention this to the orca developers. I thought it was a
caja issue. I'll be sure to follow up with you guys.
Thanks
Kendell Clark


monsta wrote:

**Comment by monsta** [comment]
Oh BTW, Caja's gksu extension is in this repo: https://github.com/mate-desktop/caja-extensions/

**Comment by monsta** [comment]
However, if it affects any app being run via gksu, then we can't do anything about it. And since gksu and libgksu are basically unmaintained upstream, chances are that some workaround has to be applied to orca...

**Comment by coffeeking** [comment]
hi
I've brought this up to the orca developers. She says she can't work
around it because she's not able to communicate with the accessibility
stack. Basically, the app is being run as root and either at-spi can't
connect to it or it's being blocked from connecting, so orca can't read
the app. Would it be possible to change caja's extension to go through
something like policy kit or pam? I believe this is what gnome does, and
apps run as root work there. I'm not criticizing, just trying to
understand how all this works.
Thanks
Kendell Clark


monsta wrote:

**Comment by monsta** [comment]
It won't solve the problem completely: Caja's gksu extension does only one job - launches another Caja instance as root. It has nothing to do with running any other app via gksu...

**Comment by coffeeking** [comment]
hi
Ah, that's right. In that case, which part of mate handles the "run as
administrator" item you get when right clicking on app icons? That,
along with caja's extension, will need to be changed to fix the
accessibility. I'm willing to help, not just file bugs. Would finding
the commit in nautilus and gnome shell where this was done help? I know
there was talk about backporting some accessibility fixes from nautilus
3.x but I'm not sure if it was ever done. Changing the subject so we
don't confuse users who are following this now closed bug.
Thanks
Kendell Clark


monsta wrote:

**Comment by monsta** [comment]
Ah... running apps via icons... well, that might be this extension as well, need to check the code.
I never tried to do that actually, all I used is opening a folder as root :smile: For me it's way faster to run apps via gksu from the terminal than browsing to /usr/bin with Caja and locating the app first.

**Comment by monsta** [comment]
Sorry, I got confused here. It's not possible to do that on apps themselves (binary files) to open them as root (will produce an error message dialog). It's only possible to do it with text files, images, Python scripts, etc. - this will run eom or pluma or something else as root, opening the selected file.
This feature is indeed in caja-gksu extension.

However, running apps with gksu via the terminal is outside of this scope.

**Comment by coffeeking** [comment]
hi
Ah, so it's not possible to run apps as root. I'm sorry, I thought it
was. And yes, the accessibility of gksu isn't something you guys can
control, only apps launched as root via desktop files or from within
caja. I'm still not sure how gnome gets around this. This feature does
need to get fixed because some system apps have to be run as root. Do
you know how I could help? I want to help, not simply complain.
Thanks
Kendell Clark


monsta wrote:

**Comment by coffeeking** [comment]
hi
It looks like it's possible to run apps as root via caja if their icon
is on the desktop. I tested by adding engrampa to the desktop, then
clicking the "run as administrator" option. It did launch once I'd
authenticated, but orca wouldn't read it.
Thanks
Kendell Clark


kendell clark wrote:

**Comment by monsta** [comment]
I see, so it can open .desktop files, and looks like caja-gksu extension is used there once again. Ok, file a report in caja-extensions repo so we'd not forget about it.

**Comment by coffeeking** [comment]
hi
Sure thing, filing now.
Thanks
Kendell Clark


monsta wrote:

**Comment by coffeeking** [comment]
hi
I've just filed the issue hear.
https://github.com/mate-desktop/caja-extensions/issues/21.
Thanks
Kendell Clark


kendell clark wrote:

**Comment by monsta** [comment]
Ok, thanks.
