### ISSUE TITLE
Please document how to enable the "Shutdown" menu

### ISSUE THREAD

**Issue by oz123** [mate-desktop/mate-session-manager#75]
I have tried to build "mate-session-manager" such the system menu includes the dialog: "shutdown"
This dialog exists when install mate from debian repositories. However when trying to install mate-session-manager from gentoo portage I can't get this dialog to work. 
My USE flags include `upower`. 

I would really appreciate some info on this.

**Comment by oz123** [comment]
If that is of any help, here is the configuration summary on my system:

```
   mate-session 1.8.1
              ==================

        prefix:                   /usr/local
        exec_prefix:              ${prefix}
        libdir:                   ${exec_prefix}/lib
        bindir:                   ${exec_prefix}/bin
        sbindir:                  ${exec_prefix}/sbin
        sysconfdir:               ${prefix}/etc
        localstatedir:            ${prefix}/var
        datadir:                  ${datarootdir}
        source code location:     .
        compiler:                 gcc
        cflags:                   -g -O2
        Maintainer mode:          no
        Warn about deprecations:  no

        GTK+ version:             2.0
        Default WM:               marco
        Systemd support:          no
        Upower support:           yes
        IPv6 support:             yes
        Backtrace support:        no
        XRender support:          yes
        XSync support:            yes
        XTest support:            yes
        Build documentation:      yes

```

**Comment by oz123** [comment]
One more observation, when starting mate as root, I can see this dialog box. So, it's some kind of permissions issue, not build issue.

**Comment by monsta** [comment]
Seems like a distro-specific issue?

**Comment by infirit** [comment]
Make sure to use ```sys-power/upower-pm-utils``` and have consolekit installed and running. Some elevated privileged actions are handled by polkit so check if you have that as well.

**Comment by oz123** [comment]
@infirit thank you! I did as you suggest, and this really works. I found this solution through people help in the IRC channel. It would be useful to others to have this as documentation in a README or build instructions.

**Comment by monsta** [comment]
Good, I guess this report can be closed now :smile:

**Comment by oz123** [comment]
No, exactly not. The issue is not how to solve it. The issue is to document it. I can make PR if you want. Where do you think is the appropriate place to document it?

**Comment by infirit** [comment]
This is very distro specific so I see no point in documenting it in a README. I suggest to document it here https://wiki.gentoo.org/wiki/MATE so future gentoo users are aware.

**Comment by oz123** [comment]
@infirit can you explain why this a distro specific issue? If someone builds mate from source on Debian won't he have that issue too?

**Comment by infirit** [comment]
```upower-pm-utils``` is a quasi fork done by one of the gentoo devs and still has the necessary bits for desktops like MATE to query and set the power state properly. The normal upower releases do not support this any-more and ppl are suggested to use logind (systemd) for these things now.

Debian 7 has an old enough upower release and debian 8 uses systemd.
