### ISSUE TITLE
double vision

### ISSUE THREAD

**Issue by JazzMaster** [mate-desktop/mate-session-manager#82]
![double vision](https://cloud.githubusercontent.com/assets/3869928/7357493/bcb9d1c2-ecf4-11e4-921e-673b27807824.png)

This keeps occuring. See http://mate-linuxbug.blogspot.com/2015/04/seeing-double.html?showComment=1430167154870 for a fix. Its temporary, though and keeps coming back.Seems to be a session cookie bug. Intermittently comes back after fix.Please keep from occuring.
##

**Comment by flexiondotorg** [comment]
What are you reporting exactly?

**Comment by monsta** [comment]
Looks like steps to reproduce are described in https://github.com/mate-desktop/mate-panel/issues/353, so let's move there.
