### ISSUE TITLE
Fix build of tools/mate-sesion-inhibit.c

### ISSUE THREAD

**Issue by obache** [mate-desktop/mate-session-manager#85]
Curerntly based on gnome-commit: fcdbf2b36b184f10239ac7a81cb3c88b4c5ed477
Please also apply folllowing f6a9ab48d29a99a1d696035a085ed8a19c33bbb8, fix missing locale.h.

**Comment by monsta** [comment]
Would be nice if you made a PR with the fix, or at least provided the direct links to upstream...

**Comment by obache** [comment]
GNOME/gnome-session@f6a9ab48d29a99a1d696035a085ed8a19c33bbb8
