### ISSUE TITLE
mate-session cannot start with closed stdin (dbus: connection refused)

### ISSUE THREAD

**Issue by brunodefraine** [mate-desktop/mate-session-manager#94]
When I tried to use mate 1.10 on a RHEL7 machine, it failed to startup and gave me an error that it could not connect to dbus. I traced this to the fact that my startup script was starting mate-session with the stdin closed. In the past, I did run gnome-session (from Gnome 2) on RHEL5.7 with stdin closed and it was no problem.

The context is that I login to the machine using SSH, and then I start an X server (for example, Xvnc) and invoke mate-session on the new display:

If I simply do:

    mate-session &>mate.log

I get a working desktop.

On the other hand, I was trying to do:

    mate-session <&- &>mate.log

And the desktop failed to start. The log contains a lot of messages regarding dbus "connection refused". I get a dialog box with a similar message.

```
mate-session[60627]: WARNING: Could not make bus activated clients aware of XDG_CURRENT_DESKTOP=MATE environment variable: Failed to connect to socket /tmp/dbus-zE5pFdXvpq: Connection refused
mate-session[60627]: WARNING: Could not make bus activated clients aware of DISPLAY=:99 environment variable: Failed to connect to socket /tmp/dbus-zE5pFdXvpq: Connection refused
mate-session[60627]: WARNING: Could not make bus activated clients aware of MATE_DESKTOP_SESSION_ID=this-is-deprecated environment variable: Failed to connect to socket /tmp/dbus-zE5pFdXvpq: Connection refused
mate-session[60627]: dconf-WARNING: failed to commit changes to dconf: Could not connect: Connection refused
mate-session[60627]: WARNING: Could not make bus activated clients aware of SESSION_MANAGER=local/unix:@/tmp/.ICE-unix/60627,unix/unix:/tmp/.ICE-unix/60627 environment variable: Failed to connect to socket /tmp/dbus-zE5pFdXvpq: Connection refused
mate-session[60627]: Gtk-CRITICAL: IA__gtk_main_quit: assertion 'main_loops != NULL' failed
mate-session[60627]: CRITICAL: dbus_g_proxy_new_for_name: assertion 'connection != NULL' failed
mate-session[60627]: Gtk-CRITICAL: IA__gtk_main_quit: assertion 'main_loops != NULL' failed
mate-session[60627]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
** Message: couldn't connect to dbus session bus: Failed to connect to socket /tmp/dbus-zE5pFdXvpq: Connection refused
mate-session[60627]: CRITICAL: error getting session bus: Failed to connect to socket /tmp/dbus-zE5pFdXvpq: Connection refused
mate-session[60627]: WARNING: Unable to register presence with session bus
mate-session[60627]: CRITICAL: dbus_g_proxy_new_for_name: assertion 'connection != NULL' failed
mate-session[60627]: CRITICAL: error getting session bus: Failed to connect to socket /tmp/dbus-zE5pFdXvpq: Connection refused
```

I expected mate-session to start with stdin closed (I close stdin to detach from my SSH connection). At the very least, this was hard to debug, because the closing of stdin was not directly on the invocation of mate-session itself, but rather on a script around it.

**Comment by brunodefraine** [comment]
Perhaps this is a problem of dbus-launch: https://bugs.freedesktop.org/show_bug.cgi?id=39197

If I first launch dbus myself:

    eval $(dbus-launch --sh-syntax)

I can invoke mate-session with stdin closed.

**Comment by infirit** [comment]
>Perhaps this is a problem of dbus-launch: https://bugs.freedesktop.org/show_bug.cgi?id=39197

Probably this is what you are running into yes. MATE relies heavily on a dbus session to be available.

**Comment by brunodefraine** [comment]
OK, looking at ``require_dbus_session`` in main.c, mate-session is re-invoking itself with ``dbus-launch --exit-with-session`` if there is no dbus yet.

I have dbus 1.6.12. If I invoke ``dbus-launch --exit-with-session <cmd>`` with closed stdin, it seems that the dbus-daemon will immediately exit; in any case, ``<cmd>`` will not be able to access the dbus instance pointed to by environment variable DBUS_SESSION_BUS_ADDRESS.

Feel free to close the issue, I'll work around it.
