### ISSUE TITLE
Windows Open Normal, But Are Difficult To Grab & Pull

### ISSUE THREAD

**Issue by mandomans** [mate-desktop/mate-session-manager#98]
I have three Mint 17.2 Mate Computers.  A Dell Inspiron N5030, and two desktop systems I built, one an AMD and the other an Asus.  This problem happens on all three computers.
After a successful boot up, after opening a file, the file behaves in an odd manner, in that when I try to drag it across screen, the file instantly opens to full screen.  I always grab on the left of a window to avoid this very problem.  I have found that the occurrence is most likely to happen if I let the top of the file meet the bottom of the upper panel, but it can happen any time during a drag across screen.
I have been updated, and upgraded to the hilt, and the problem persists.  I have long since tried finding the cure in Caja Preferences, but am not able to find anything that even relates to this occurrence.
If this isn't a bug, please illuminate me.  Thanks.

**Comment by monsta** [comment]
Try this: ```mate-window-properties``` ```->``` Placement tab ```->``` uncheck "Enable side by side tiling"

**Comment by monsta** [comment]
Anyway, even if it wasn't an issue with tiling, it would be a problem in the window manager (Marco), not the session manager.
If the suggested solution didn't work, please file a new report at:
https://github.com/mate-desktop/marco/issues
