### ISSUE TITLE
typo in g_warning in gs-idle-monitor.c

### ISSUE THREAD

**Issue by sunweaver** [mate-desktop/mate-session-manager#99]
There is a typo in a g_warning (existant -> existent). Patch comes in a sec.

**Comment by sunweaver** [comment]
http://anonscm.debian.org/cgit/pkg-mate/mate-session-manager.git/plain/debian/patches/1003_typo-fix.patch?id=f319219828aca539f9caf8862b35d1631e964af5

**Comment by monsta** [comment]
Thanks, fixed in https://github.com/mate-desktop/mate-session-manager/commit/5014a4ddbdf8349fe8206cf3df3ac6a97361b469.
